### ISSUE TITLE
android-sdk failed to build on ubuntu

### ISSUE THREAD

**Issue by jdrouet** [Linuxbrew/homebrew-core#1049]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._
### Bug reports:

Tried to install android-sdk using `brew install android-sdk`
https://gist.github.com/anonymous/6c51c9e4eb03a9ea034ad5329b9ba7a6
### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by sjackman** [comment]
```
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
	at javax.crypto.JceSecurity.<clinit>(java.base@9-Ubuntu/JceSecurity.java:91)
	... 48 more
Caused by: java.lang.NullPointerException
	at sun.nio.fs.UnixPath.normalizeAndCheck(java.base@9-Ubuntu/UnixPath.java:75)
```
https://gist.github.com/anonymous/6c51c9e4eb03a9ea034ad5329b9ba7a6#file-01-android-L56

**Comment by worthwhileindustries** [comment]
Mine failed with this
```
==> echo y | bash /home/tristan/.linuxbrew/Cellar/android-sdk/24.4.1_1/bin/android --verbose update sdk --no-ui --all --filter platform-tools,build-tools-23.0.1
Error: uninitialized constant Formulary::FormulaNamespacedee1db78bcd3e509f526a19ce2b341fa::AndroidSdk::MachO
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/tristan/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/android-sdk.rb:113:in `block in install'
/home/tristan/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/android-sdk.rb:112:in `each'
/home/tristan/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/android-sdk.rb:112:in `install'
/home/tristan/.linuxbrew/Library/Homebrew/build.rb:149:in `block in install'
/home/tristan/.linuxbrew/Library/Homebrew/formula.rb:1135:in `block in brew'
/home/tristan/.linuxbrew/Library/Homebrew/formula.rb:1928:in `block in stage'
/home/tristan/.linuxbrew/Library/Homebrew/resource.rb:98:in `block in unpack'
/home/tristan/.linuxbrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/tristan/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/tristan/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/tristan/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/tristan/.linuxbrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/tristan/.linuxbrew/Library/Homebrew/resource.rb:94:in `unpack'
/home/tristan/.linuxbrew/Library/Homebrew/resource.rb:86:in `stage'
/home/tristan/.linuxbrew/Library/Homebrew/formula.rb:1915:in `stage'
/home/tristan/.linuxbrew/Library/Homebrew/formula.rb:1130:in `brew'
/home/tristan/.linuxbrew/Library/Homebrew/build.rb:124:in `install'
/home/tristan/.linuxbrew/Library/Homebrew/build.rb:201:in `<main>'
```

**Comment by sjackman** [comment]
Attempting to reproduce at https://github.com/Linuxbrew/homebrew-core/pull/2023
