### ISSUE TITLE
gdb: Error: uninitialized constant ELF::ArchitectureListExtension

### ISSUE THREAD

**Issue by ZeldaZach** [Linuxbrew/homebrew-core#1106]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

Attempted to update GDB from 7.11.1 to 7.12. Error messages from terminal included:
```
Error: uninitialized constant ELF::ArchitectureListExtension

/import/linux/home/zhalper3/.linuxbrew/Library/Homebrew/os/linux/elf.rb:73:in `archs'
/import/linux/home/zhalper3/.linuxbrew/Library/Homebrew/utils.rb:405:in `archs_for_command'
/import/linux/home/zhalper3/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/gdb.rb:2:in `block in <class:UniversalBrewedPython>'
/import/linux/home/zhalper3/.linuxbrew/Library/Homebrew/requirement.rb:57:in `instance_eval'
/import/linux/home/zhalper3/.linuxbrew/Library/Homebrew/requirement.rb:57:in `block in satisfied?'
/import/linux/home/zhalper3/.linuxbrew/Library/Homebrew/requirement.rb:184:in `block in yielder'
/import/linux/home/zhalper3/.linuxbrew/Library/Homebrew/extend/ENV.rb:25:in `with_build_environment'
/import/linux/home/zhalper3/.linuxbrew/Library/Homebrew/requirement.rb:184:in `yielder'
/import/linux/home/zhalper3/.linuxbrew/Library/Homebrew/requirement.rb:57:in `satisfied?'
/import/linux/home/zhalper3/.linuxbrew/Library/Homebrew/build.rb:51:in `block in expand_reqs'
/import/linux/home/zhalper3/.linuxbrew/Library/Homebrew/requirement.rb:216:in `block in prune?'
/import/linux/home/zhalper3/.linuxbrew/Library/Homebrew/requirement.rb:214:in `catch'
/import/linux/home/zhalper3/.linuxbrew/Library/Homebrew/requirement.rb:214:in `prune?'
/import/linux/home/zhalper3/.linuxbrew/Library/Homebrew/requirement.rb:205:in `block (2 levels) in expand'
/import/linux/home/zhalper3/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/lib/ruby/2.0.0/set.rb:232:in `each_key'
/import/linux/home/zhalper3/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/lib/ruby/2.0.0/set.rb:232:in `each'
/import/linux/home/zhalper3/.linuxbrew/Library/Homebrew/dependencies.rb:68:in `each'
/import/linux/home/zhalper3/.linuxbrew/Library/Homebrew/requirement.rb:204:in `block in expand'
/import/linux/home/zhalper3/.linuxbrew/Library/Homebrew/requirement.rb:203:in `each'
/import/linux/home/zhalper3/.linuxbrew/Library/Homebrew/requirement.rb:203:in `expand'
/import/linux/home/zhalper3/.linuxbrew/Library/Homebrew/formula.rb:1455:in `recursive_requirements'
/import/linux/home/zhalper3/.linuxbrew/Library/Homebrew/build.rb:45:in `expand_reqs'
/import/linux/home/zhalper3/.linuxbrew/Library/Homebrew/build.rb:27:in `initialize'
/import/linux/home/zhalper3/.linuxbrew/Library/Homebrew/build.rb:186:in `new'
/import/linux/home/zhalper3/.linuxbrew/Library/Homebrew/build.rb:186:in `<main>'
```
No gist-logs were found, sorry about that. I'm here to help with any steps needed to figure out the issue. Please note that this is a school server, so updating computer packages cannot be done so easily.

**Comment by sjackman** [comment]
This error should be fixed by 0f97d761ca896d6c9a9a9a1fd6c538857606b9e3
Please try `brew update` and install `gdb`
Just to confirm, were you trying `brew install gdb --with-python` ?

**Comment by ZeldaZach** [comment]
@sjackman Yes, I was using the `--with-python` flag. This seems to work as expected now. Thanks for the quick fix!

**Comment by sjackman** [comment]
Glad it worked!
