### ISSUE TITLE
Installing gettext fails on Ubuntu

### ISSUE THREAD

**Issue by paradox460** [Linuxbrew/homebrew-core#1220]
Trying to install ffmpeg, and it depends on gettext. Looks like merging in 1.0.8 made `#xz_dep` a private method inside dependency collector, in [89696b](https://github.com/Linuxbrew/brew/commit/89696bd4fe11e8fedf6c05d99e8db784f06214ee#diff-d6e8980dbd56c3c8468438181a406381)

```
brew install gettext
==> Downloading https://ftpmirror.gnu.org/gettext/gettext-0.19.8.1.tar.xz
Already downloaded: /home/jeffs/.cache/Homebrew/gettext-0.19.8.1.tar.xz
Error: private method `xz_dep' called for #<DependencyCollector:0x005646388b2160>
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/jeffs/.linuxbrew/Library/Homebrew/dependency_collector.rb:65:in `tar_needs_xz_dependency?'
/home/jeffs/.linuxbrew/Library/Homebrew/download_strategy.rb:244:in `block in stage'
/home/jeffs/.linuxbrew/Library/Homebrew/utils.rb:255:in `with_system_path'
/home/jeffs/.linuxbrew/Library/Homebrew/download_strategy.rb:243:in `stage'
/home/jeffs/.linuxbrew/Library/Homebrew/resource.rb:95:in `block in unpack'
/home/jeffs/.linuxbrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/jeffs/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/jeffs/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/jeffs/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/jeffs/.linuxbrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/jeffs/.linuxbrew/Library/Homebrew/resource.rb:94:in `unpack'
/home/jeffs/.linuxbrew/Library/Homebrew/resource.rb:86:in `stage'
/home/jeffs/.linuxbrew/Library/Homebrew/formula.rb:1799:in `stage'
/home/jeffs/.linuxbrew/Library/Homebrew/formula.rb:1075:in `brew'
/home/jeffs/.linuxbrew/Library/Homebrew/build.rb:112:in `install'
/home/jeffs/.linuxbrew/Library/Homebrew/build.rb:187:in `<main>'
```

**Comment by paradox460** [comment]
Resetting my brew to b1a16deb190ae5ccb05b60a3dd10b53eaf1bae15 and i can install gettext

**Comment by rwhogg** [comment]
This issue was moved to Linuxbrew/brew#180
