### ISSUE TITLE
docker-compose failed to build on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by ganimp84** [Linuxbrew/homebrew-core#1223]
### Bug reports:

`brew gist-logs docker-compose`
https://gist.github.com/fd9816e76dca31c1209f2dc393bd6a66

Trying to install docker-compose on Ubuntu 16.04 LTS using brew. It fails at the following step...

```
==> /home/user/.linuxbrew/Cellar/docker-compose/1.8.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/docker-compose--PyYAML-20161201-25005-j3cbs5/PyYAML-3.12
Last 15 lines from /home/user/.cache/Homebrew/Logs/docker-compose/13.pip:
  Removing source in /tmp/pip-U4T1fj-build
Command "/home/user/.linuxbrew/Cellar/docker-compose/1.8.1/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-U4T1fj-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-JCzonc-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/.linuxbrew/Cellar/docker-compose/1.8.1/libexec/include/site/python2.7/PyYAML" failed with error code 1 in /tmp/pip-U4T1fj-build/
Exception information:
Traceback (most recent call last):
  File "/home/user/.linuxbrew/Cellar/docker-compose/1.8.1/libexec/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/user/.linuxbrew/Cellar/docker-compose/1.8.1/libexec/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/user/.linuxbrew/Cellar/docker-compose/1.8.1/libexec/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/user/.linuxbrew/Cellar/docker-compose/1.8.1/libexec/local/lib/python2.7/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/home/user/.linuxbrew/Cellar/docker-compose/1.8.1/libexec/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/home/user/.linuxbrew/Cellar/docker-compose/1.8.1/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-U4T1fj-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-JCzonc-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/.linuxbrew/Cellar/docker-compose/1.8.1/libexec/include/site/python2.7/PyYAML" failed with error code 1 in /tmp/pip-U4T1fj-build/
```

**Comment by sjackman** [comment]
I'm attempting to reproduce this bug at PR https://github.com/Linuxbrew/homebrew-core/pull/1225

**Comment by sjackman** [comment]
```
    /usr/bin/gcc-5 -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Os -w -pipe -march=native -isystem/home/gani/.linuxbrew/include -fPIC -I/usr/include/python2.7 -c ext/_yaml.c -o build/temp.linux-x86_64-2.7/ext/_yaml.o
    ext/_yaml.c:4:20: fatal error: Python.h: No such file or directory
```
https://gist.github.com/anonymous/fd9816e76dca31c1209f2dc393bd6a66#file-13-pip-L62

Try `brew install python docker-compose`

**Comment by sjackman** [comment]
I've built a precompiled binary bottle for `docker-compse`. If you now try `brew install docker-compse`, it will download this bottle, and you won't have to compile from source.

**Comment by ganimp84** [comment]
Thanks for helping me on this. I have tried again and the installation completed successfully. But, when I try any docker-compose commands, it's giving me these errors

```
$ docker-compose --version
Traceback (most recent call last):
  File "/home/user/.linuxbrew/bin/docker-compose", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/user/.linuxbrew/Cellar/docker-compose/1.8.1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 18, in <module>
    from __future__ import absolute_import
ImportError: No module named __future__
```

**Comment by sjackman** [comment]
Please report `python --version` and try `brew install python docker-compose`

**Comment by rwhogg** [comment]
@sjackman I think `no module named __future__` sounds familiar. IIRC I had the same problem with the `flake8` bottle and had to revert it.

I think bottles and virtualenv's on Linuxbrew don't like each other for some reason :from

**Comment by ganimp84** [comment]
@sjackman 

```
$ which -a python
/home/gani/.linuxbrew/bin/python
/usr/bin/python
```

I also tried `brew install python docker-compose` it ends up again with the same problem `ImportError: No module named __future__`

**Comment by sjackman** [comment]
I can confirm that I also see this error. The following work around works for me:
```sh
export PYTHONPATH=`brew --prefix python`/lib/python2.7
docker-compose --version
```

**Comment by sjackman** [comment]
@rwhogg [`virtualenv_install_with_resources`](https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/language/python.rb#L161) doesn't work out of the box on Linuxbrew. We'll have to patch it up to set the `PYTHONPATH` appropriately for Linuxbrew.

**Comment by sjackman** [comment]
Steps to reproduce the error for debugging:
```sh
cd `brew --prefix docker-compose`/libexec
source bin/activate
python -c 'from __future__ import print_function'
ImportError: No module named __future__
```

**Comment by sjackman** [comment]
```
❯❯❯ bin/python -c 'import sys; print sys.path' |grep -o "'/home/linuxbrew[^ ]*'"
'/home/linuxbrew/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7'
```
Yep. So that bottle is not relocatable. I wonder why it's tagged as `cellar :any` on Mac, and I wonder whether this bug affects Mac? Also tied to the specific version of the `python` keg, which isn't great.

The workaround is easy enough, so not high priority (for me, anyway), but would be nice to fix it.

**Comment by sjackman** [comment]
https://virtualenv.pypa.io/en/stable/userguide/#making-environments-relocatable

> Making Environments Relocatable
Note: this option is somewhat experimental, and there are probably caveats that have not yet been identified.
Warning
The --relocatable option currently has a number of issues, and is not guaranteed to work in all circumstances. It is possible that the option will be deprecated in a future version of virtualenv.
