### ISSUE TITLE
homebrew/fuse/s3fs: Error: wrong number of arguments (0 for 1..3)

### ISSUE THREAD

**Issue by ylluminate** [Linuxbrew/homebrew-core#1818]
While trying to install homebrew/fuse/s3fs, I received the following error:

`$ brew install homebrew/fuse/s3fs`
```
==> Tapping homebrew/fuse
Cloning into '/home/admin/.linuxbrew/Library/Taps/homebrew/homebrew-fuse'...
remote: Counting objects: 34, done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 34 (delta 0), reused 15 (delta 0), pack-reused 0
Unpacking objects: 100% (34/34), done.
Tapped 28 formulae (86 files, 265.8K)
==> Installing s3fs from homebrew/fuse
Error: wrong number of arguments (0 for 1..3)
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:58:in `instance_eval'
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:58:in `block in satisfied?'
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:196:in `block in yielder'
/home/admin/.linuxbrew/Library/Homebrew/extend/ENV.rb:25:in `with_build_environment'
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:196:in `yielder'
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:58:in `satisfied?'
/home/admin/.linuxbrew/Library/Homebrew/formula_installer.rb:414:in `block in expand_requirements'
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:228:in `block in prune?'
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:226:in `catch'
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:226:in `prune?'
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:217:in `block (2 levels) in expand'
/usr/share/ruby/set.rb:232:in `each_key'
/usr/share/ruby/set.rb:232:in `each'
/home/admin/.linuxbrew/Library/Homebrew/dependencies.rb:68:in `each'
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:216:in `block in expand'
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:215:in `each'
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:215:in `expand'
/home/admin/.linuxbrew/Library/Homebrew/formula.rb:1521:in `recursive_requirements'
/home/admin/.linuxbrew/Library/Homebrew/formula_installer.rb:402:in `expand_requirements'
/home/admin/.linuxbrew/Library/Homebrew/formula_installer.rb:347:in `compute_dependencies'
/home/admin/.linuxbrew/Library/Homebrew/formula_installer.rb:135:in `verify_deps_exist'
/home/admin/.linuxbrew/Library/Homebrew/formula_installer.rb:128:in `prelude'
/home/admin/.linuxbrew/Library/Homebrew/cmd/install.rb:324:in `install_formula'
/home/admin/.linuxbrew/Library/Homebrew/cmd/install.rb:199:in `block in install'
/home/admin/.linuxbrew/Library/Homebrew/cmd/install.rb:199:in `each'
/home/admin/.linuxbrew/Library/Homebrew/cmd/install.rb:199:in `install'
/home/admin/.linuxbrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by ylluminate** [comment]
Same thing when I installed ruby 2.4:
```
==> Installing s3fs from homebrew/fuse
Error: wrong number of arguments (given 0, expected 1..3)
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:58:in `instance_eval'
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:58:in `block in satisfied?'
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:196:in `block in yielder'
/home/admin/.linuxbrew/Library/Homebrew/extend/ENV.rb:25:in `with_build_environment'
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:196:in `yielder'
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:58:in `satisfied?'
/home/admin/.linuxbrew/Library/Homebrew/formula_installer.rb:414:in `block in expand_requirements'
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:228:in `block in prune?'
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:226:in `catch'
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:226:in `prune?'
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:217:in `block (2 levels) in expand'
/home/admin/.linuxbrew/Cellar/ruby/2.4.0/lib/ruby/2.4.0/set.rb:324:in `each_key'
/home/admin/.linuxbrew/Cellar/ruby/2.4.0/lib/ruby/2.4.0/set.rb:324:in `each'
/home/admin/.linuxbrew/Library/Homebrew/dependencies.rb:68:in `each'
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:216:in `block in expand'
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:215:in `each'
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:215:in `expand'
/home/admin/.linuxbrew/Library/Homebrew/formula.rb:1521:in `recursive_requirements'
/home/admin/.linuxbrew/Library/Homebrew/formula_installer.rb:402:in `expand_requirements'
/home/admin/.linuxbrew/Library/Homebrew/formula_installer.rb:347:in `compute_dependencies'
/home/admin/.linuxbrew/Library/Homebrew/formula_installer.rb:135:in `verify_deps_exist'
/home/admin/.linuxbrew/Library/Homebrew/formula_installer.rb:128:in `prelude'
/home/admin/.linuxbrew/Library/Homebrew/cmd/install.rb:324:in `install_formula'
/home/admin/.linuxbrew/Library/Homebrew/cmd/install.rb:199:in `block in install'
/home/admin/.linuxbrew/Library/Homebrew/cmd/install.rb:199:in `each'
/home/admin/.linuxbrew/Library/Homebrew/cmd/install.rb:199:in `install'
/home/admin/.linuxbrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by timotheecour** [comment]
@ylluminate please add formula in title, eg:
`homebrew/fuse/s3fs: Error: wrong number of arguments (0 for 1..3) #1818`

**Comment by timotheecour** [comment]
I fixed it :) 
https://github.com/Homebrew/homebrew-fuse/pull/107
