### ISSUE TITLE
homebrew/fuse/sshfs: Error: wrong number of arguments (0 for 1..3)

### ISSUE THREAD

**Issue by asanakoy** [Linuxbrew/homebrew-core#1917]
Cannot install 'homebrew/fuse/sshfs'. I get this error.
Brew is up-to-date, 'brew doctor' didn't help.

`:~$ brew install homebrew/fuse/sshfs`
```
==> Installing sshfs from homebrew/fuse
Error: wrong number of arguments (0 for 1..3)
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/export/home/asanakoy/.linuxbrew/Library/Homebrew/requirement.rb:58:in `instance_eval'
/export/home/asanakoy/.linuxbrew/Library/Homebrew/requirement.rb:58:in `block in satisfied?'
/export/home/asanakoy/.linuxbrew/Library/Homebrew/requirement.rb:196:in `block in yielder'
/export/home/asanakoy/.linuxbrew/Library/Homebrew/extend/ENV.rb:29:in `with_build_environment'
/export/home/asanakoy/.linuxbrew/Library/Homebrew/requirement.rb:196:in `yielder'
/export/home/asanakoy/.linuxbrew/Library/Homebrew/requirement.rb:58:in `satisfied?'
/export/home/asanakoy/.linuxbrew/Library/Homebrew/formula_installer.rb:416:in `block in expand_requirements'
/export/home/asanakoy/.linuxbrew/Library/Homebrew/requirement.rb:228:in `block in prune?'
/export/home/asanakoy/.linuxbrew/Library/Homebrew/requirement.rb:226:in `catch'
/export/home/asanakoy/.linuxbrew/Library/Homebrew/requirement.rb:226:in `prune?'
/export/home/asanakoy/.linuxbrew/Library/Homebrew/requirement.rb:217:in `block (2 levels) in expand'
/usr/lib/ruby/2.1.0/set.rb:263:in `each_key'
/usr/lib/ruby/2.1.0/set.rb:263:in `each'
/export/home/asanakoy/.linuxbrew/Library/Homebrew/dependencies.rb:68:in `each'
/export/home/asanakoy/.linuxbrew/Library/Homebrew/requirement.rb:216:in `block in expand'
/export/home/asanakoy/.linuxbrew/Library/Homebrew/requirement.rb:215:in `each'
/export/home/asanakoy/.linuxbrew/Library/Homebrew/requirement.rb:215:in `expand'
/export/home/asanakoy/.linuxbrew/Library/Homebrew/formula.rb:1521:in `recursive_requirements'
/export/home/asanakoy/.linuxbrew/Library/Homebrew/formula_installer.rb:404:in `expand_requirements'
/export/home/asanakoy/.linuxbrew/Library/Homebrew/formula_installer.rb:349:in `compute_dependencies'
/export/home/asanakoy/.linuxbrew/Library/Homebrew/formula_installer.rb:135:in `verify_deps_exist'
/export/home/asanakoy/.linuxbrew/Library/Homebrew/formula_installer.rb:128:in `prelude'
/export/home/asanakoy/.linuxbrew/Library/Homebrew/cmd/install.rb:324:in `install_formula'
/export/home/asanakoy/.linuxbrew/Library/Homebrew/cmd/install.rb:199:in `block in install'
/export/home/asanakoy/.linuxbrew/Library/Homebrew/cmd/install.rb:199:in `each'
/export/home/asanakoy/.linuxbrew/Library/Homebrew/cmd/install.rb:199:in `install'
/export/home/asanakoy/.linuxbrew/Library/Homebrew/brew.rb:94:in `<main>'
asanakoy@machine:~/.local/bin$ curl: /export/home/asanakoy/.linuxbrew/lib64/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
curl: /export/home/asanakoy/.linuxbrew/lib64/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
curl: /export/home/asanakoy/.linuxbrew/lib64/libcrypto.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)

```
```

:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.7 (jessie)
Release:	8.7
Codename:	jessie
```

**Comment by sjackman** [comment]
Hi, Artsiom. It's a known issue. Sorry. @rwhogg is working on it. @
