### ISSUE TITLE
glibc: Error: Failure while executing: ["ldd", "~/.linuxbrew/Cellar/glibc/2.19/lib/libc-2.19.so"]

### ISSUE THREAD

**Issue by niemasd** [Linuxbrew/homebrew-core#2796]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
    - `brew doctor` wants me to update git with `brew install git`, but git requires glibc, which is what is triggering this
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
    - `brew gist-logs glibc`: https://gist.github.com/f53fa0278e78d53c9ccbc9a0272293cb
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
    - `brew gist-logs glibc` worked, but I've included the output of `brew config` and `brew doctor` just in case

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

On CentOS 5.8 (Final), I was trying to set up Linuxbrew to simplify tool installation (I don't have root access). Pretty much everything needs glibc (e.g. python3 and gcc), so I was trying to install it. The same exact error occurs when I try to install git (the existing version is out-of-date, and `brew doctor` wanted me to update it with `brew install git`).

Below is the end of `brew install glibc -dv`:
```
if test -r /scratchfast/a1moshir/.linuxbrew/Cellar/glibc/2.19/include/gnu/stubs-64.h && cmp -s /tmp/glibc-20170529-27343-12xc9pb/glibc-2.19/build/stubs.h /scratchfast/a1moshir/.linuxbrew/Cellar/glibc/2.19/include/gnu/stubs-64.h; \
        then echo 'stubs.h unchanged'; \
        else /usr/bin/install -c -m 644 /tmp/glibc-20170529-27343-12xc9pb/glibc-2.19/build/stubs.h /scratchfast/a1moshir/.linuxbrew/Cellar/glibc/2.19/include/gnu/stubs-64.h; fi
rm -f /tmp/glibc-20170529-27343-12xc9pb/glibc-2.19/build/stubs.h
/tmp/glibc-20170529-27343-12xc9pb/glibc-2.19/build/elf/sln /tmp/glibc-20170529-27343-12xc9pb/glibc-2.19/build/elf/symlink.list
rm -f /tmp/glibc-20170529-27343-12xc9pb/glibc-2.19/build/elf/symlink.list
test ! -x /tmp/glibc-20170529-27343-12xc9pb/glibc-2.19/build/elf/ldconfig || LC_ALL=C LANGUAGE=C \
          /tmp/glibc-20170529-27343-12xc9pb/glibc-2.19/build/elf/ldconfig  \
                                       /scratchfast/a1moshir/.linuxbrew/Cellar/glibc/2.19/lib /scratchfast/a1moshir/.linuxbrew/Cellar/glibc/2.19/lib
/tmp/glibc-20170529-27343-12xc9pb/glibc-2.19/build/elf/ldconfig: Warning: ignoring configuration file that cannot be opened: /scratchfast/a1moshir/.linuxbrew/Cellar/glibc/2.19/etc/ld.so.conf: No such file or directory
make[1]: Leaving directory `/tmp/glibc-20170529-27343-12xc9pb/glibc-2.19'
==> Kept temporary files
Temporary files retained at /tmp/glibc-20170529-27343-12xc9pb
Error: Failure while executing: ["ldd", "/scratchfast/a1moshir/.linuxbrew/Cellar/glibc/2.19/lib/libc-2.19.so"]
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/debrew.rb:11:in `raise'
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/os/linux/elf.rb:52:in `initialize'
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/os/linux/elf.rb:93:in `new'
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/os/linux/elf.rb:93:in `metadata'
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/os/linux/elf.rb:104:in `dynamically_linked_libraries'
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:58:in `block in detect_cxx_stdlibs'
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:56:in `each'
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:56:in `detect_cxx_stdlibs'
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/cxxstdlib.rb:26:in `check_compatibility'
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/build.rb:169:in `detect_stdlibs'
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/build.rb:152:in `block in install'
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/formula.rb:1148:in `block in brew'
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/formula.rb:1955:in `block in stage'
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/resource.rb:98:in `block in unpack'
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/resource.rb:94:in `unpack'
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/resource.rb:86:in `stage'
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/formula.rb:1936:in `stage'
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/formula.rb:1143:in `brew'
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/build.rb:125:in `install'
/scratchfast/a1moshir/.linuxbrew/Library/Homebrew/build.rb:202:in `<main>'
```

The results of `brew gist-logs glibc` can be found here: https://gist.github.com/f53fa0278e78d53c9ccbc9a0272293cb

The output of `brew config` can be found here:
```
HOMEBREW_VERSION: >1.1.0 (no git repository)
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: 03aff74ad46b5bb6469e36808181b5ed18667a6d
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: e2db4e7ee1e214cdb2443364602a8eb5b9fa8e2b
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /scratchfast/a1moshir/.linuxbrew
HOMEBREW_REPOSITORY: /scratchfast/a1moshir/.linuxbrew
HOMEBREW_CELLAR: /scratchfast/a1moshir/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: 32-core 64-bit nehalem
Homebrew Ruby: 2.0.0-p648 => /scratchfast/a1moshir/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Clang: N/A
Git: 1.7.4.1 => /usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.6.0_23
Kernel: Linux 2.6.18-308.4.1.el5 x86_64 GNU/Linux
OS: CentOS release 5.8 (Final) (Final)
Host glibc: 2.5
/usr/bin/gcc: 4.1.2
glibc: N/A
gcc: N/A
xorg: N/A
```

The output of `brew doctor` can be found here:
```
Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /usr/kerberos/bin/krb5-config

Warning: An outdated version (1.7.4.1) of Git was detected in your PATH.
Git 1.8.5 or newer is required to perform checkouts over HTTPS from GitHub and
to support the 'git -C <path>' option.
Please upgrade:
  brew install git
```

These are the exact commands I ran from starting with nothing:
```bash
# set all languages to English (needed when glibc postinstall complains about language)
export LANG=en_US.UTF-8
export LC_CTYPE="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_PAPER="en_US.UTF-8"
export LC_NAME="en_US.UTF-8"
export LC_ADDRESS="en_US.UTF-8"
export LC_TELEPHONE="en_US.UTF-8"
export LC_MEASUREMENT="en_US.UTF-8"
export LC_IDENTIFICATION="en_US.UTF-8"

# install linuxbrew
git clone https://github.com/Linuxbrew/brew.git ~/.linuxbrew

# set up PATHs
export PATH="$HOME/.linuxbrew/bin:$HOME/.linuxbrew/sbin:$PATH"
export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"

# symlink the system compilers
for f in /usr/bin/gcc*; do ln -s `which $f` $HOME/.linuxbrew/bin/gcc-`$f -dumpversion |cut -d. -f1,2`; done
for f in /usr/bin/g++*; do ln -s `which $f` $HOME/.linuxbrew/bin/g++-`$f -dumpversion |cut -d. -f1,2`; done
for f in /usr/bin/gfortran*; do ln -s `which $f` $HOME/.linuxbrew/bin/gfortran-`$f -dumpversion | grep "GNU Fortran (GCC)" | cut -f4 -d' '`; done
rm $HOME/.linuxbrew/bin/*- # I have a file /usr/bin/gccmakedep, which results in the symlink "gccmakedep-"

# install stuff
brew install zlib # success
brew install binutils --with-default-names # success
brew install linux-headers # success
brew install glibc --with-current-kernel # fail
```

**Comment by sjackman** [comment]
> symlink the system compilers

This step is no longer necessary. `brew` now does it automatically for you.

**Comment by niemasd** [comment]
> symlink the system compilers
>>This step is no longer necessary. brew now does it automatically for you.

The system's default compiler (`/usr/bin/gcc`) is gcc-4.1, so the brew automatic symlink was getting that one, and it was causing giving the following error:

```
Error: glibc cannot be built with any available compilers.
Install Clang or brew install gcc
```

The system has gcc-4.4 as well (`/usr/bin/gcc44`), so symlinking that one as well fixed the error, which is why I add that step

**Comment by sjackman** [comment]
> `brew install binutils --with-default-names`

You can omit `--with-default-names`. It's the default.

**Comment by sjackman** [comment]
> The system has gcc-4.4 as well (/usr/bin/gcc44), so symlinking that one as well fixed the error, which is why I add that step

Right. Thank you for reminding me about that. It'd be nice if Linuxbrew took care of that as well, but it doesn't currently.

**Comment by niemasd** [comment]
> You can omit `--with-default-names`. It's the default.

I was unaware of this, thanks!

**Comment by sjackman** [comment]
```
Kernel: Linux 2.6.18-308.4.1.el5 x86_64 GNU/Linux
OS: CentOS release 5.8 (Final) (Final)
Host glibc: 2.5
```
https://gist.github.com/anonymous/f53fa0278e78d53c9ccbc9a0272293cb#file-00-config-out-L22

I suspect that `/bin/ldd` from the hosts's glibc 2.5 is being used, and it's failing.

**Comment by sjackman** [comment]
Please try the following patch.
```diff
diff --git a/Library/Homebrew/os/linux/elf.rb b/Library/Homebrew/os/linux/elf.rb
index 576cdeffc..c6fe37ee1 100644
--- a/Library/Homebrew/os/linux/elf.rb
+++ b/Library/Homebrew/os/linux/elf.rb
@@ -49,7 +49,11 @@ module ELF
       end
       command = ["ldd", path.expand_path.to_s]
       libs = Utils.popen_read(*command).split("\n")
-      raise ErrorDuringExecution, command unless $?.success?
+      unless $?.success?
+        opoo "Failure while executing: #{command}"
+        @dylibs = needed
+        return
+      end
       needed << "not found"
       libs.select! { |lib| needed.any? { |soname| lib.include? soname } }
       @dylibs = libs.map { |lib| lib[LDD_RX, 1] || lib[LDD_RX, 2] }.compact
```

**Comment by sjackman** [comment]
Or better, please try this patch:
```diff
diff --git a/Library/Homebrew/os/linux/elf.rb b/Library/Homebrew/os/linux/elf.rb
index 576cdeffc..e8a1a8cea 100644
--- a/Library/Homebrew/os/linux/elf.rb
+++ b/Library/Homebrew/os/linux/elf.rb
@@ -47,7 +47,9 @@ module ELF
         @dylibs = []
         return
       end
-      command = ["ldd", path.expand_path.to_s]
+      ldd = Formula["glibc"].bin/"ldd"
+      ldd = "ldd" unless ldd.executable?
+      command = [ldd, path.expand_path.to_s]
       libs = Utils.popen_read(*command).split("\n")
       raise ErrorDuringExecution, command unless $?.success?
       needed << "not found"
```

**Comment by niemasd** [comment]
You are amazing! It installed without any issues after making the change you suggested. I'm trying out `brew install git` right now to see if things that depend on glibc install properly now. Thanks so much!

**Comment by sjackman** [comment]
Glad to hear it, Niema. Which patch did you use, the first or the second?

**Comment by niemasd** [comment]
I used the second

**Comment by sjackman** [comment]
This issue should be resolved by PR https://github.com/Linuxbrew/brew/pull/398

**Comment by niemasd** [comment]
No problem, thanks for all of your help!

**Comment by sjackman** [comment]
No worries. Happy to help.
