### ISSUE TITLE
Error: brew install docker-compose

### ISSUE THREAD

**Issue by Nezteb** [Linuxbrew/homebrew-core#2998]
Tried `brew update` twice and `brew doctor` to no avail.

Gist log: https://gist.github.com/anonymous/cf2c93921517039a6fe56a78af7d555d

Screenshot of error:
![screenshot_2017-06-20_09-49-17](https://user-images.githubusercontent.com/3588798/27347920-cb569d90-559e-11e7-9ce1-93cd4eef26b8.png)

**Comment by sjackman** [comment]
Please copy-and-paste the error message rather than taking a screen shot.
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by sjackman** [comment]
I'm attempting to reproduce this issue at PR https://github.com/Linuxbrew/homebrew-core/pull/3000.

**Comment by Nezteb** [comment]
My apologies.

The error in text:
```
==> Installing docker-compose 
==> Downloading https://github.com/docker/compose/archive/1.13.0.tar.gz
Already downloaded: /home/noah/.cache/Homebrew/docker-compose-1.13.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/5c/79/5dae7494b9f5ed061cff9a8ab8d6e1f02db352f3facf907d9eb614fb80e9/virtualenv-15.0.2.tar.gz
Already downloaded: /home/noah/.cache/Homebrew/docker-compose--homebrew-virtualenv-15.0.2.tar.gz
==> python -c import setuptools... —no-user-cfg install —prefix=/tmp/docker-compose--homebrew-virtualenv-20170620-3785-lcek6t/target —single-version-externally-managed —record=installed.txt
==> python -s /tmp/docker-compose--homebrew-virtualenv-20170620-3785-lcek6t/target/bin/virtualenv -p python /home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.13.0/libexec
==> /home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.13.0/libexec/bin/pip install -v —no-binary :all: —ignore-installed /tmp/docker-compose-20170620-3785-7cpx78/compose-1.13.0
Last 15 lines from /home/noah/.cache/Homebrew/Logs/docker-compose/03.pip:
  Removing source in /tmp/pip-build-dYH88v/functools32
Command "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.13.0/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-dYH88v/PyYAML/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install —record /tmp/pip-iLgQoz-record/install-record.txt —single-version-externally-managed —compile —install-headers /home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.13.0/libexec/include/site/python2.7/PyYAML" failed with error code 1 in /tmp/pip-build-dYH88v/PyYAML/
Exception information:
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.13.0/libexec/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.13.0/libexec/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.13.0/libexec/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.13.0/libexec/local/lib/python2.7/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.13.0/libexec/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.13.0/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-dYH88v/PyYAML/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install —record /tmp/pip-iLgQoz-record/install-record.txt —single-version-externally-managed —compile —install-headers /home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.13.0/libexec/include/site/python2.7/PyYAML" failed with error code 1 in /tmp/pip-build-dYH88v/PyYAML/
```

Also I found [#1223](https://github.com/Linuxbrew/homebrew-core/issues/1223) which is related, but lists a workaround instead of an actual fix. For now it will work.

**Comment by sjackman** [comment]
I've built a bottle for `docker-compose`. You should find that `brew update && brew install docker-compose` works now.
