### ISSUE TITLE
openssl: Error: Unsupported special dependency :perl

### ISSUE THREAD

**Issue by girishentriver** [Linuxbrew/homebrew-core#3155]
Info 1:
```
brew install node
Error: Unsupported special dependency :perl
Please report this bug:
    https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/girish/.linuxbrew/Library/Homebrew/dependency_collector.rb:123:in `parse_symbol_spec'
/home/girish/.linuxbrew/Library/Homebrew/compat/dependency_collector.rb:17:in `parse_symbol_spec'
/home/girish/.linuxbrew/Library/Homebrew/dependency_collector.rb:73:in `parse_spec'
/home/girish/.linuxbrew/Library/Homebrew/dependency_collector.rb:61:in `build'
/home/girish/.linuxbrew/Library/Homebrew/dependency_collector.rb:48:in `block in fetch'
/home/girish/.linuxbrew/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/home/girish/.linuxbrew/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/home/girish/.linuxbrew/Library/Homebrew/dependency_collector.rb:38:in `add'
/home/girish/.linuxbrew/Library/Homebrew/software_spec.rb:155:in `depends_on'
/home/girish/.linuxbrew/Library/Homebrew/formula.rb:1862:in `block in depends_on'
/home/girish/.linuxbrew/Library/Homebrew/formula.rb:1862:in `each'
/home/girish/.linuxbrew/Library/Homebrew/formula.rb:1862:in `depends_on'
/home/girish/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb:37:in `<class:Openssl>'
/home/girish/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb:4:in `load_formula'
/home/girish/.linuxbrew/Library/Homebrew/formulary.rb:21:in `module_eval'
/home/girish/.linuxbrew/Library/Homebrew/formulary.rb:21:in `load_formula'
/home/girish/.linuxbrew/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/home/girish/.linuxbrew/Library/Homebrew/formulary.rb:83:in `load_file'
/home/girish/.linuxbrew/Library/Homebrew/formulary.rb:74:in `klass'
/home/girish/.linuxbrew/Library/Homebrew/formulary.rb:70:in `get_formula'
/home/girish/.linuxbrew/Library/Homebrew/formulary.rb:207:in `factory'
/home/girish/.linuxbrew/Library/Homebrew/dependency.rb:32:in `to_formula'
/home/girish/.linuxbrew/Library/Homebrew/formula_installer.rb:381:in `block in expand_dependencies'
/home/girish/.linuxbrew/Library/Homebrew/dependency.rb:106:in `block in action'
/home/girish/.linuxbrew/Library/Homebrew/dependency.rb:104:in `catch'
/home/girish/.linuxbrew/Library/Homebrew/dependency.rb:104:in `action'
/home/girish/.linuxbrew/Library/Homebrew/dependency.rb:83:in `block in expand'
/home/girish/.linuxbrew/Library/Homebrew/dependency.rb:80:in `each'
/home/girish/.linuxbrew/Library/Homebrew/dependency.rb:80:in `expand'
/home/girish/.linuxbrew/Library/Homebrew/formula_installer.rb:375:in `expand_dependencies'
/home/girish/.linuxbrew/Library/Homebrew/formula_installer.rb:265:in `compute_dependencies'
/home/girish/.linuxbrew/Library/Homebrew/formula_installer.rb:130:in `verify_deps_exist'
/home/girish/.linuxbrew/Library/Homebrew/formula_installer.rb:123:in `prelude'
/home/girish/.linuxbrew/Library/Homebrew/cmd/install.rb:231:in `install_formula'
/home/girish/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `block in install'
/home/girish/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `each'
/home/girish/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `install'
/home/girish/.linuxbrew/Library/brew.rb:84:in `<main>'
```

Info 2: I tried "brew update"  to retry brew install node, but "brew update" also failed log is shown below
```
$ brew update
remote: Counting objects: 1049, done.
remote: Compressing objects: 100% (976/976), done.
remote: Total 1049 (delta 185), reused 335 (delta 41), pack-reused 0
Receiving objects: 100% (1049/1049), 1.22 MiB | 185.00 KiB/s, done.
Resolving deltas: 100% (185/185), completed with 95 local objects.
From https://github.com/Linuxbrew/brew
 + eec5059...089f4ed master     -> origin/master  (forced update)
HEAD is now at 089f4ed Re-add myself as a maintainer (#420)
/home/girish/.linuxbrew/Library/Homebrew/cmd/update.sh: line 6: /home/girish/.linuxbrew/Library/ENV/scm/git: No such file or directory
```

Info 3 brew doctor output:
```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Setting LD_* vars can break dynamic linking.
Set variables:
  LD_LIBRARY_PATH: :/usr/local/apr/lib:
Warning: Calling Utils::Shell.shell_profile is deprecated!
Use Utils::Shell.profile instead.
/home/girish/.linuxbrew/Library/Homebrew/diagnostic.rb:499:in `check_xdg_data_dirs'


Warning: Homebrew's share was not found in your XDG_DATA_DIRS but you have
this variable set to include other locations.
Some programs like `vapigen` may not work correctly.
Consider setting the XDG_DATA_DIRS for example like so
    echo 'export XDG_DATA_DIRS="/home/girish/.linuxbrew/share:$XDG_DATA_DIRS"' >> ~/.bash_profile
```

**Comment by sjackman** [comment]
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by sjackman** [comment]
As a temporary work-around, try running `brew edit openssl`, deleting the line `depends_on :perl => ["5.0", :build]`, then run `brew install node`

**Comment by sjackman** [comment]
I'm not able to reproduce this error with either `brew` 1.2.2 or the `master` branch. Please report…
```sh
brew --version
brew config
```
Try…
```sh
brew --version
brew update
brew --version
brew install node
```
