### ISSUE TITLE
shellcheck: cabal: The following packages are likely to be broken by the reinstalls

### ISSUE THREAD

**Issue by chubin** [Linuxbrew/homebrew-core#464]
I can't install shellcheck now (strange, but it seems to work yesterday):

```
$ brew install shellcheck
==> Downloading https://github.com/koalaman/shellcheck/archive/v0.4.3.tar.gz
Already downloaded: /nfs/home/ic8448/.cache/Homebrew/shellcheck-0.4.3.tar.gz
==> cabal sandbox init
==> cabal update
==> cabal install --jobs=48 --max-backjumps=100000 --only-dependencies
Last 15 lines from /nfs/home/ic8448/.cache/Homebrew/Logs/shellcheck/03.cabal:

Resolving dependencies...
In order, the following would be installed:
transformers-0.5.2.0 (new version)
QuickCheck-2.8.2 -base4point8 (new version)
mtl-2.2.1 (new version)
parsec-3.1.11 (new version)
json-0.9.1 (new package)
regex-base-0.93.2 (reinstall) changes: mtl-2.1.3.1 -> 2.2.1
regex-tdfa-1.2.2 (new package)
cabal: The following packages are likely to be broken by the reinstalls:
regex-posix-0.95.2
regex-compat-0.95.1
haskell-platform-2014.2.0.0.2
Use --force-reinstalls if you want to install anyway.

READ THIS: https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Linuxbrew/homebrew-core/issues

/z/ic8448/.ccc/p/brew/Library/Homebrew/exceptions.rb:357:in `dump': undefined method `check_for_unsupported_osx' for #<Homebrew::Diagnostic::Checks:0x005636d1586278> (NoMethodError)
        from /z/ic8448/.ccc/p/brew/Library/brew.rb:133:in `rescue in <main>'
        from /z/ic8448/.ccc/p/brew/Library/brew.rb:29:in `<main>'
```

**Comment by chubin** [comment]
But it works if I add ` --force-reinstalls` (as recommended in the output)

**Comment by sjackman** [comment]
Attempt to reproduce over here: https://github.com/Linuxbrew/homebrew-core/pull/466
