### ISSUE TITLE
homebrew/python/retext: ImportError: No module named 'PyQt5' 

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/homebrew-core#474]
```
brew install retext
retext

Traceback (most recent call last):
  File "/home/timothee/.linuxbrew/Cellar/retext/5.2.1/retext", line 22, in <module>
    from ReText import datadirs, globalSettings, app_version
  File "/home/timothee/.linuxbrew/Cellar/retext/5.2.1/lib/python3.5/site-packages/ReText/__init__.py", line 21, in <module>
    from PyQt5.QtCore import QByteArray, QLocale, QSettings, QStandardPaths
ImportError: No module named 'PyQt5'

brew install pyqt5

Last 15 lines from /home/timothee/.cache/Homebrew/Logs/qt5/01.configure:
xcb.cpp:39:23: warning: unused variable 't' [-Wunused-variable]
     xcb_connection_t *t = xcb_connect("", &primaryScreen);
                       ^
g++ -Wl,-O1 -o xcb xcb.o   -lxcb
xcb enabled.
xcb-syslibs auto-detection... ()
g++ -c -pipe -O2 -Wall -W -fPIC  -I. -I../../../mkspecs/linux-g++ -o xcb.o xcb.cpp
xcb.cpp:38:27: fatal error: xcb/xcb_icccm.h: No such file or directory
compilation terminated.
Makefile:172: recipe for target 'xcb.o' failed
make: *** [xcb.o] Error 1
xcb-syslibs disabled.
The test for linking against libxcb and support libraries failed!
 You might need to install dependency packages, or pass -qt-xcb.
 See src/plugins/platforms/xcb/README.
```

**Comment by rwhogg** [comment]
According to https://github.com/retext-project/retext/blob/master/changelog.md, `retext` has not supported Qt 4.x since version 5.0, but that's the version Linuxbrew tries to install.

Unfortunately, last I checked Qt 5 does not build on Linux. See https://github.com/Linuxbrew/homebrew-core/issues/146 . I haven't had time to work on that recently, but if you can help out with it it would be greatly appreciated.

Would you like to open a PR upstream to homebrew/homebrew-python that changes the dependency on `pyqt` to a dependency on `pyqt5`? I think the dependency is incorrect. If not, I can just open an issue there.

Thanks!

**Comment by rwhogg** [comment]
PR submitted upstream to homebrew-python, so closing as this isn't a Linux-specific issue.
