### ISSUE TITLE
brew install gsl fails. Please Help, I'm quite new to brew

### ISSUE THREAD

**Issue by 3rico** [Linuxbrew/homebrew-core#4994]
With whatever i try installing anything including gsl, brew exits with the following error:

```
Updating Homebrew...
==> Installing dependencies for gsl: glibc, xz, m4, gmp, mpfr, libmpc, isl, gcc
Error: comparison of Version::FromURL with #<Class:0x0000000294fa00> failed
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/maina/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb:5:in `>='
/home/maina/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb:5:in `block in <class:BrewedGlibcNotOlderRequirement>'
/home/maina/.linuxbrew/Library/Homebrew/requirement.rb:56:in `instance_eval'
/home/maina/.linuxbrew/Library/Homebrew/requirement.rb:56:in `block in satisfied?'
/home/maina/.linuxbrew/Library/Homebrew/requirement.rb:205:in `yielder'
/home/maina/.linuxbrew/Library/Homebrew/requirement.rb:56:in `satisfied?'
/home/maina/.linuxbrew/Library/Homebrew/formula_installer.rb:459:in `block in expand_requirements'
/home/maina/.linuxbrew/Library/Homebrew/requirement.rb:235:in `block in prune?'
/home/maina/.linuxbrew/Library/Homebrew/requirement.rb:233:in `catch'
/home/maina/.linuxbrew/Library/Homebrew/requirement.rb:233:in `prune?'
/home/maina/.linuxbrew/Library/Homebrew/requirement.rb:224:in `block (2 levels) in expand'
/home/maina/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:306:in `each_key'
/home/maina/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:306:in `each'
/home/maina/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/delegate.rb:341:in `block in delegating_block'
/home/maina/.linuxbrew/Library/Homebrew/requirement.rb:223:in `block in expand'
/home/maina/.linuxbrew/Library/Homebrew/requirement.rb:222:in `each'
/home/maina/.linuxbrew/Library/Homebrew/requirement.rb:222:in `expand'
/home/maina/.linuxbrew/Library/Homebrew/formula.rb:1482:in `recursive_requirements'
/home/maina/.linuxbrew/Library/Homebrew/formula_installer.rb:445:in `expand_requirements'
/home/maina/.linuxbrew/Library/Homebrew/formula_installer.rb:379:in `compute_dependencies'
/home/maina/.linuxbrew/Library/Homebrew/formula_installer.rb:137:in `verify_deps_exist'
/home/maina/.linuxbrew/Library/Homebrew/formula_installer.rb:130:in `prelude'
/home/maina/.linuxbrew/Library/Homebrew/formula_installer.rb:604:in `install_dependency'
/home/maina/.linuxbrew/Library/Homebrew/formula_installer.rb:567:in `block in install_dependencies'
/home/maina/.linuxbrew/Library/Homebrew/formula_installer.rb:567:in `each'
/home/maina/.linuxbrew/Library/Homebrew/formula_installer.rb:567:in `install_dependencies'
/home/maina/.linuxbrew/Library/Homebrew/formula_installer.rb:259:in `install'
/home/maina/.linuxbrew/Library/Homebrew/cmd/install.rb:372:in `install_formula'
/home/maina/.linuxbrew/Library/Homebrew/cmd/install.rb:227:in `block in install'
/home/maina/.linuxbrew/Library/Homebrew/cmd/install.rb:225:in `each'
/home/maina/.linuxbrew/Library/Homebrew/cmd/install.rb:225:in `install'
/home/maina/.linuxbrew/Library/Homebrew/brew.rb:100:in `<main>'
```

brew config gives:

```
HOMEBREW_VERSION: 1.3.7
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: c8864c2243b76adaa0e373175a8cd5bd7294a4a2
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: cde85c35f1d876f621f1ae8d7b1edf37f64681e2
Core tap last commit: 2 days ago
HOMEBREW_PREFIX: /home/maina/.linuxbrew
HOMEBREW_REPOSITORY: /home/maina/.linuxbrew
HOMEBREW_CELLAR: /home/maina/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/maina/.cache/Homebrew
HOMEBREW_CELLAR: /home/maina/.linuxbrew/Cellar
HOMEBREW_GIT_CONFIG_FILE: /home/maina/.linuxbrew/.git/config
HOMEBREW_PREFIX: /home/maina/.linuxbrew
HOMEBREW_REPOSITORY: /home/maina/.linuxbrew
CPU: 32-core 64-bit sandybridge
Homebrew Ruby: 2.3.3 => /home/maina/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: N/A
Git: 2.7.4 => /usr/bin/git
Curl: 7.47.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby2.3
Java: openjdk version "1.8.0_151"
Kernel: Linux 4.4.0-87-generic x86_64 GNU/Linux
OS: Ubuntu 16.04.2 LTS (xenial)
Host glibc: N/A
/usr/bin/gcc: 5.4.0
glibc: N/A
gcc: N/A
xorg: N/A
```

brew doctor gives:

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Setting LD_* vars can break dynamic linking.
Set variables:
  LD_PRELOAD: /usr/lib/libmpi.so.12:
  LD_LIBRARY_PATH: /home/maina/.linuxbrew/lib64:/home/maina/.linuxbrew/lib:/home/maina/PolyChord/lib/:/opt/aips/31DEC16/LNX64/LIBR/INTELCMP:/opt/aips/31DEC16/LNX64/LIBR/INTELCMP
```

Please Help

**Comment by iMichka** [comment]
I edited your message and put the logs inside triple quotes.

Seems this is failing in the glibc formula:
```
Error: comparison of Version::FromURL with #<Class:0x0000000294fa00> failed
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/maina/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb:5:in `>='
```

I see that brew doctor says:
> Host glibc: N/A

How is that possible? I think without glibc you shouldn't even be able to boot your computer. Could you double check where glibc is installed? Maybe brew should look at a different place on you system, but your setup seems to be broken.

**Comment by iMichka** [comment]
Closing this, as I think there is a problem with your setup. We can reopen this or continue to discuss you issue here if you have more information. Thanks.
