### ISSUE TITLE
wine: build failed

### ISSUE THREAD

**Issue by Char-Aznable** [Linuxbrew/homebrew-core#6017]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
I'm trying to brew install wine and get the error:
```
==> Downloading https://dl.winehq.org/wine/source/3.0/wine-3.0.tar.xz
Already downloaded: /scratch/.cache/wine-3.0.tar.xz
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/74c2566/wine/2.14.patch
Already downloaded: /scratch/.cache/wine--patch-6907471d18996ada60cc0cbc8462a1698e90720c0882846dfbfb163e5d3899b8.patch
==> Patching
==> Applying 2.14.patch
patching file dlls/wined3d/context.c
Hunk #1 succeeded at 1600 (offset 169 lines).
Hunk #2 succeeded at 1629 (offset 169 lines).
Hunk #3 succeeded at 1652 (offset 169 lines).
Hunk #4 succeeded at 1680 (offset 169 lines).
Hunk #5 succeeded at 1981 (offset 196 lines).
==> Downloading https://www.openssl.org/source/openssl-1.0.2n.tar.gz
Already downloaded: /scratch/.cache/wine--openssl-1.0.2n.tar.gz
/scratch/.linuxbrew/Homebrew/Library/Homebrew/build.rb:204:in `dump': singleton class can't be dumped (TypeError)
	from /scratch/.linuxbrew/Homebrew/Library/Homebrew/build.rb:204:in `rescue in <main>'
	from /scratch/.linuxbrew/Homebrew/Library/Homebrew/build.rb:193:in `<main>'
Error: Forked child process failed: pid 31744 exit 1
```
Here's brew config output:
```
HOMEBREW_VERSION: 1.5.1-2-g8ccb999
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 8ccb999ac04fa9fcb4df521004be5eeff9fd8ba6
Last commit: 25 hours ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: daf56b83697042e256851fbe69668a0e22474fae
Core tap last commit: 24 minutes ago
HOMEBREW_PREFIX: /scratch/.linuxbrew
HOMEBREW_REPOSITORY: /scratch/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /scratch/.linuxbrew/Cellar
HOMEBREW_CACHE: /scratch/.cache
HOMEBREW_CELLAR: /scratch/.linuxbrew/Cellar
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_LOGS: /scratch/.cache
HOMEBREW_PREFIX: /scratch/.linuxbrew
HOMEBREW_REPOSITORY: /scratch/.linuxbrew/Homebrew
HOMEBREW_TEMP: /scratch/tmp
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /scratch/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 5.0 build 
Git: 2.15.1 => /scratch/.linuxbrew/bin/git
Curl: 7.58.0 => /scratch/.linuxbrew/opt/curl/bin/curl
Perl: /home/linuxbrew/.linuxbrew/bin/perl => /scratch/.linuxbrew/Cellar/perl/5.26.1/bin/perl
Python: /scratch/.linuxbrew/opt/python/libexec/bin/python => /scratch/.linuxbrew/Cellar/python/2.7.14_4/bin/python2.7
Ruby: /home/linuxbrew/.linuxbrew/bin/ruby => /scratch/.linuxbrew/Cellar/ruby/2.5.0/bin/ruby
Java: openjdk version "1.8.0_144"
Kernel: Linux 2.6.32-696.18.7.el6.x86_64 x86_64 GNU/Linux
OS: CentOS release 6.9 (Final) (Final)
Host glibc: 2.12
/usr/bin/gcc: 4.4.7
glibc: 2.23
gcc: 5.5.0_1
xorg: 20170115_1
```
and here's brew doctor output
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /home/linuxbrew/.linuxbrew/bin/icu-config
  /home/linuxbrew/.linuxbrew/bin/xslt-config
  /home/linuxbrew/.linuxbrew/bin/fcitx4-config
  /home/linuxbrew/.linuxbrew/bin/python3.6m-config
  /home/linuxbrew/.linuxbrew/bin/python2.7-config
  /home/linuxbrew/.linuxbrew/bin/Magick++-config
  /home/linuxbrew/.linuxbrew/bin/nspr-config
  /home/linuxbrew/.linuxbrew/bin/sdl2-config
  /home/linuxbrew/.linuxbrew/bin/freetype-config
  /home/linuxbrew/.linuxbrew/bin/MagickCore-config
  /home/linuxbrew/.linuxbrew/bin/libgcrypt-config
  /home/linuxbrew/.linuxbrew/bin/croco-0.6-config
  /home/linuxbrew/.linuxbrew/bin/gpg-error-config
  /home/linuxbrew/.linuxbrew/bin/gdlib-config
  /home/linuxbrew/.linuxbrew/bin/xml2-config
  /home/linuxbrew/.linuxbrew/bin/ncurses6-config
  /home/linuxbrew/.linuxbrew/bin/pkg-config
  /home/linuxbrew/.linuxbrew/bin/llvm-config
  /home/linuxbrew/.linuxbrew/bin/gsl-config
  /home/linuxbrew/.linuxbrew/bin/ncursesw6-config
  /home/linuxbrew/.linuxbrew/bin/libwmf-config
  /home/linuxbrew/.linuxbrew/bin/pcre-config
  /home/linuxbrew/.linuxbrew/bin/python3-config
  /home/linuxbrew/.linuxbrew/bin/jemalloc-config
  /home/linuxbrew/.linuxbrew/bin/pspell-config
  /home/linuxbrew/.linuxbrew/bin/caca-config
  /home/linuxbrew/.linuxbrew/bin/guile-config
  /home/linuxbrew/.linuxbrew/bin/MagickWand-config
  /home/linuxbrew/.linuxbrew/bin/python2-config
  /home/linuxbrew/.linuxbrew/bin/libpng-config
  /home/linuxbrew/.linuxbrew/bin/libpng16-config
  /home/linuxbrew/.linuxbrew/bin/wx-config
  /home/linuxbrew/.linuxbrew/bin/curl-config
  /home/linuxbrew/.linuxbrew/bin/cups-config
  /home/linuxbrew/.linuxbrew/bin/orbit2-config
  /home/linuxbrew/.linuxbrew/bin/krb5-config
  /home/linuxbrew/.linuxbrew/bin/autoopts-config
  /home/linuxbrew/.linuxbrew/bin/python3.6-config

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  lua@5.1
  lapack
Warning: Calling 'depends_on :python' is deprecated!
Use 'depends_on "python"' instead.
/scratch/.linuxbrew/Homebrew/Library/Homebrew/dependency_collector.rb:88:in `parse_spec'

Warning: Calling 'depends_on :python3' is deprecated!
Use 'depends_on "python3"' instead.
/scratch/.linuxbrew/Homebrew/Library/Homebrew/dependency_collector.rb:88:in `parse_spec'

Warning: Use tcl-tk instead of deprecated homebrew/dupes/tcl-tk
Warning: Use tcl-tk instead of deprecated homebrew/dupes/tcl-tk
```

**Comment by iMichka** [comment]
Hi. I can reproduce this. If I print the content of the variable that is being dumped; we get:
`uninitialized constant #<Class:Hardware::CPU>::ArchitectureListExtension`

Maybe these lines are the culprit:
https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/wine.rb#L164-L170

**Comment by Poetastrophe** [comment]
Is this issue going to be fixed anytime soon? I saw that you were able to build a bottle for a similar issue with zookeeper: [here](https://github.com/Linuxbrew/homebrew-core/pull/7440), but I do not possess the know-how to do it myself, and I don't know if the fix is as trivial.
