### ISSUE TITLE
Unable to install Python libraries with C extensions

### ISSUE THREAD

**Issue by thedrow** [Linuxbrew/homebrew-core#6553]
I'm unable to install thefuck and other libraries since for some reason the headers are missing.
I have python-dev and python3-dev installed on my computer.
Could it be that brew sets the include path wrongly somehow?

```
brew install thefuck --verbose
==> Downloading https://files.pythonhosted.org/packages/ec/20/3f136313c27ea36ba38d31818b9f0a1a4656668fc6747b3bfa04f3debc98/thefuck-3.25.tar.gz
Already downloaded: /home/omer/.cache/Homebrew/thefuck-3.25.tar.gz
==> Verifying thefuck-3.25.tar.gz checksum
tar xzf /home/omer/.cache/Homebrew/thefuck-3.25.tar.gz
==> Downloading https://files.pythonhosted.org/packages/d4/0c/9840c08189e030873387a73b90ada981885010dd9aea134d6de30cd24cb8/virtualenv-15.1.0.tar.gz
Already downloaded: /home/omer/.cache/Homebrew/thefuck--homebrew-virtualenv-15.1.0.tar.gz
==> Verifying thefuck--homebrew-virtualenv-15.1.0.tar.gz checksum
tar xzf /home/omer/.cache/Homebrew/thefuck--homebrew-virtualenv-15.1.0.tar.gz
==> python2 -c import setuptools... --no-user-cfg install --prefix=/tmp/thefuck--homebrew-virtualenv-20180313-1543-1beky1w/target --single-version-externally-managed --record=installed.txt
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
copying virtualenv.py -> build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/virtualenv_support
copying virtualenv_support/__init__.py -> build/lib.linux-x86_64-2.7/virtualenv_support
copying virtualenv_support/argparse-1.4.0-py2.py3-none-any.whl -> build/lib.linux-x86_64-2.7/virtualenv_support
copying virtualenv_support/setuptools-28.8.0-py2.py3-none-any.whl -> build/lib.linux-x86_64-2.7/virtualenv_support
copying virtualenv_support/pip-9.0.1-py2.py3-none-any.whl -> build/lib.linux-x86_64-2.7/virtualenv_support
copying virtualenv_support/wheel-0.29.0-py2.py3-none-any.whl -> build/lib.linux-x86_64-2.7/virtualenv_support
running install_lib
creating /tmp/thefuck--homebrew-virtualenv-20180313-1543-1beky1w/target/lib/python2.7/site-packages/virtualenv_support
copying build/lib.linux-x86_64-2.7/virtualenv_support/argparse-1.4.0-py2.py3-none-any.whl -> /tmp/thefuck--homebrew-virtualenv-20180313-1543-1beky1w/target/lib/python2.7/site-packages/virtualenv_support
copying build/lib.linux-x86_64-2.7/virtualenv_support/__init__.py -> /tmp/thefuck--homebrew-virtualenv-20180313-1543-1beky1w/target/lib/python2.7/site-packages/virtualenv_support
copying build/lib.linux-x86_64-2.7/virtualenv_support/setuptools-28.8.0-py2.py3-none-any.whl -> /tmp/thefuck--homebrew-virtualenv-20180313-1543-1beky1w/target/lib/python2.7/site-packages/virtualenv_support
copying build/lib.linux-x86_64-2.7/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl -> /tmp/thefuck--homebrew-virtualenv-20180313-1543-1beky1w/target/lib/python2.7/site-packages/virtualenv_support
copying build/lib.linux-x86_64-2.7/virtualenv_support/wheel-0.29.0-py2.py3-none-any.whl -> /tmp/thefuck--homebrew-virtualenv-20180313-1543-1beky1w/target/lib/python2.7/site-packages/virtualenv_support
copying build/lib.linux-x86_64-2.7/virtualenv.py -> /tmp/thefuck--homebrew-virtualenv-20180313-1543-1beky1w/target/lib/python2.7/site-packages
byte-compiling /tmp/thefuck--homebrew-virtualenv-20180313-1543-1beky1w/target/lib/python2.7/site-packages/virtualenv_support/__init__.py to __init__.pyc
byte-compiling /tmp/thefuck--homebrew-virtualenv-20180313-1543-1beky1w/target/lib/python2.7/site-packages/virtualenv.py to virtualenv.pyc
running install_egg_info
running egg_info
writing virtualenv.egg-info/PKG-INFO
writing top-level names to virtualenv.egg-info/top_level.txt
writing dependency_links to virtualenv.egg-info/dependency_links.txt
writing entry points to virtualenv.egg-info/entry_points.txt
reading manifest file 'virtualenv.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*' found under directory 'docs/_templates'
warning: no previously-included files matching '*' found under directory 'docs/_build'
writing manifest file 'virtualenv.egg-info/SOURCES.txt'
Copying virtualenv.egg-info to /tmp/thefuck--homebrew-virtualenv-20180313-1543-1beky1w/target/lib/python2.7/site-packages/virtualenv-15.1.0-py2.7.egg-info
running install_scripts
Installing virtualenv script to /tmp/thefuck--homebrew-virtualenv-20180313-1543-1beky1w/target/bin
writing list of installed files to 'installed.txt'
==> python2 -s /tmp/thefuck--homebrew-virtualenv-20180313-1543-1beky1w/target/bin/virtualenv -p python2 /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec
Already using interpreter /usr/bin/python2
New python executable in /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/bin/python2
Also creating executable in /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/bin/python
Installing setuptools, pip, wheel...done.
==> Downloading https://files.pythonhosted.org/packages/e6/76/257b53926889e2835355d74fec73d82662100135293e17d382e2b74d1669/colorama-0.3.9.tar.gz
Already downloaded: /home/omer/.cache/Homebrew/thefuck--colorama-0.3.9.tar.gz
==> Verifying thefuck--colorama-0.3.9.tar.gz checksum
tar xzf /home/omer/.cache/Homebrew/thefuck--colorama-0.3.9.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/thefuck--colorama-20180313-1543-46c0fn/colorama-0.3.9
Processing /tmp/thefuck--colorama-20180313-1543-46c0fn/colorama-0.3.9
  Running setup.py (path:/tmp/pip-AjaIbS-build/setup.py) egg_info for package from file:///tmp/thefuck--colorama-20180313-1543-46c0fn/colorama-0.3.9
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/colorama.egg-info
    writing pip-egg-info/colorama.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/colorama.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/colorama.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/colorama.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/colorama.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/colorama.egg-info/SOURCES.txt'
  Source in /tmp/pip-AjaIbS-build has version 0.3.9, which satisfies requirement colorama==0.3.9 from file:///tmp/thefuck--colorama-20180313-1543-46c0fn/colorama-0.3.9
Skipping bdist_wheel for colorama, due to binaries being disabled for it.
Installing collected packages: colorama
  Running setup.py install for colorama: started
    Running command /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-AjaIbS-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-dryv8t-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/include/site/python2.7/colorama
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/colorama
    copying colorama/ansitowin32.py -> build/lib.linux-x86_64-2.7/colorama
    copying colorama/__init__.py -> build/lib.linux-x86_64-2.7/colorama
    copying colorama/winterm.py -> build/lib.linux-x86_64-2.7/colorama
    copying colorama/ansi.py -> build/lib.linux-x86_64-2.7/colorama
    copying colorama/win32.py -> build/lib.linux-x86_64-2.7/colorama
    copying colorama/initialise.py -> build/lib.linux-x86_64-2.7/colorama
    running install_lib
    creating /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/lib/python2.7/site-packages/colorama
    copying build/lib.linux-x86_64-2.7/colorama/ansitowin32.py -> /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/lib/python2.7/site-packages/colorama
    copying build/lib.linux-x86_64-2.7/colorama/__init__.py -> /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/lib/python2.7/site-packages/colorama
    copying build/lib.linux-x86_64-2.7/colorama/winterm.py -> /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/lib/python2.7/site-packages/colorama
    copying build/lib.linux-x86_64-2.7/colorama/ansi.py -> /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/lib/python2.7/site-packages/colorama
    copying build/lib.linux-x86_64-2.7/colorama/win32.py -> /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/lib/python2.7/site-packages/colorama
    copying build/lib.linux-x86_64-2.7/colorama/initialise.py -> /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/lib/python2.7/site-packages/colorama
    byte-compiling /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/lib/python2.7/site-packages/colorama/ansitowin32.py to ansitowin32.pyc
    byte-compiling /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/lib/python2.7/site-packages/colorama/__init__.py to __init__.pyc
    byte-compiling /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/lib/python2.7/site-packages/colorama/winterm.py to winterm.pyc
    byte-compiling /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/lib/python2.7/site-packages/colorama/ansi.py to ansi.pyc
    byte-compiling /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/lib/python2.7/site-packages/colorama/win32.py to win32.pyc
    byte-compiling /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/lib/python2.7/site-packages/colorama/initialise.py to initialise.pyc
    running install_egg_info
    running egg_info
    writing colorama.egg-info/PKG-INFO
    writing top-level names to colorama.egg-info/top_level.txt
    writing dependency_links to colorama.egg-info/dependency_links.txt
    reading manifest file 'colorama.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'colorama.egg-info/SOURCES.txt'
    Copying colorama.egg-info to /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/lib/python2.7/site-packages/colorama-0.3.9-py2.7.egg-info
    running install_scripts
    writing list of installed files to '/tmp/pip-dryv8t-record/install-record.txt'
    Running setup.py install for colorama: finished with status 'done'
  Removing source in /tmp/pip-AjaIbS-build
Successfully installed colorama-0.3.9
Cleaning up...
==> Downloading https://files.pythonhosted.org/packages/bb/e0/f6e41e9091e130bf16d4437dabbac3993908e4d6485ecbc985ef1352db94/decorator-4.1.2.tar.gz
Already downloaded: /home/omer/.cache/Homebrew/thefuck--decorator-4.1.2.tar.gz
==> Verifying thefuck--decorator-4.1.2.tar.gz checksum
tar xzf /home/omer/.cache/Homebrew/thefuck--decorator-4.1.2.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/thefuck--decorator-20180313-1543-8yvfrv/decorator-4.1.2
Processing /tmp/thefuck--decorator-20180313-1543-8yvfrv/decorator-4.1.2
  Running setup.py (path:/tmp/pip-mZf30X-build/setup.py) egg_info for package from file:///tmp/thefuck--decorator-20180313-1543-8yvfrv/decorator-4.1.2
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/decorator.egg-info
    writing pip-egg-info/decorator.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/decorator.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/decorator.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/decorator.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/decorator.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'documentation.pdf'
    writing manifest file 'pip-egg-info/decorator.egg-info/SOURCES.txt'
  Source in /tmp/pip-mZf30X-build has version 4.1.2, which satisfies requirement decorator==4.1.2 from file:///tmp/thefuck--decorator-20180313-1543-8yvfrv/decorator-4.1.2
Skipping bdist_wheel for decorator, due to binaries being disabled for it.
Installing collected packages: decorator
  Running setup.py install for decorator: started
    Running command /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-mZf30X-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-dDOEWI-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/include/site/python2.7/decorator
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    copying src/decorator.py -> build/lib.linux-x86_64-2.7
    running install_lib
    copying build/lib.linux-x86_64-2.7/decorator.py -> /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/lib/python2.7/site-packages
    byte-compiling /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/lib/python2.7/site-packages/decorator.py to decorator.pyc
    running install_egg_info
    running egg_info
    writing src/decorator.egg-info/PKG-INFO
    writing top-level names to src/decorator.egg-info/top_level.txt
    writing dependency_links to src/decorator.egg-info/dependency_links.txt
    reading manifest file 'src/decorator.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'documentation.pdf'
    writing manifest file 'src/decorator.egg-info/SOURCES.txt'
    Copying src/decorator.egg-info to /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/lib/python2.7/site-packages/decorator-4.1.2-py2.7.egg-info
    running install_scripts
    writing list of installed files to '/tmp/pip-dDOEWI-record/install-record.txt'
    Running setup.py install for decorator: finished with status 'done'
  Removing source in /tmp/pip-mZf30X-build
Successfully installed decorator-4.1.2
Cleaning up...
==> Downloading https://files.pythonhosted.org/packages/fe/17/0f0bf5792b2dfe6003efc5175c76225f7d3426f88e2bf8d360cfab870cd8/psutil-5.4.1.tar.gz
Already downloaded: /home/omer/.cache/Homebrew/thefuck--psutil-5.4.1.tar.gz
==> Verifying thefuck--psutil-5.4.1.tar.gz checksum
tar xzf /home/omer/.cache/Homebrew/thefuck--psutil-5.4.1.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/thefuck--psutil-20180313-1543-1cu6epg/psutil-5.4.1
Processing /tmp/thefuck--psutil-20180313-1543-1cu6epg/psutil-5.4.1
  Running setup.py (path:/tmp/pip-b0ZHJO-build/setup.py) egg_info for package from file:///tmp/thefuck--psutil-20180313-1543-1cu6epg/psutil-5.4.1
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/psutil.egg-info
    writing requirements to pip-egg-info/psutil.egg-info/requires.txt
    writing pip-egg-info/psutil.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/psutil.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/psutil.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/psutil.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/psutil.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/psutil.egg-info/SOURCES.txt'
  Source in /tmp/pip-b0ZHJO-build has version 5.4.1, which satisfies requirement psutil==5.4.1 from file:///tmp/thefuck--psutil-20180313-1543-1cu6epg/psutil-5.4.1
Skipping bdist_wheel for psutil, due to binaries being disabled for it.
Installing collected packages: psutil
  Running setup.py install for psutil: started
    Running command /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-b0ZHJO-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-nIMZIZ-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/include/site/python2.7/psutil
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psbsd.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/__init__.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psposix.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_pswindows.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_pslinux.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psaix.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_pssunos.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psosx.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_compat.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_common.py -> build/lib.linux-x86_64-2.7/psutil
    creating build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/__init__.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_memory_leaks.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/__main__.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_process.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_system.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-2.7/psutil/tests
    running build_ext
    building 'psutil._psutil_linux' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/psutil
    gcc-7 -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-l1RrwO/python2.7-2.7.14=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=541 -DPSUTIL_LINUX=1 -I/usr/include/python2.7 -c psutil/_psutil_common.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_common.o
    psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc-7' failed with exit status 1
    Running setup.py install for psutil: finished with status 'error'
Cleaning up...
  Removing source in /tmp/pip-b0ZHJO-build
Command "/home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-b0ZHJO-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-nIMZIZ-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/include/site/python2.7/psutil" failed with error code 1 in /tmp/pip-b0ZHJO-build/
Exception information:
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/local/lib/python2.7/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-b0ZHJO-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-nIMZIZ-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_3/libexec/include/site/python2.7/psutil" failed with error code 1 in /tmp/pip-b0ZHJO-build/

==> Formula
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/thefuck.rb
==> Configuration
HOMEBREW_VERSION: 1.5.8
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 0da98e625677eeff4b772be3508d9528e56ca686
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: a15aa1068e06269231bf306e0e718ddfa85fcc66
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/omer/.cache/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_ENABLE_AUTO_UPDATE_MIGRATION: 1
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_RUBY_WARNINGS: -W0
CPU: octa-core 64-bit 0x69e
Homebrew Ruby: 2.3.3 => /usr/bin/ruby2.3
Clang: 4.0 build 
Git: 2.16.2 => /usr/bin/git
Curl: 7.55.1 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /home/linuxbrew/.linuxbrew/opt/python/libexec/bin/python => /home/linuxbrew/.linuxbrew/Cellar/python/3.6.4_5/bin/python3.6
Ruby: /usr/bin/ruby => /usr/bin/ruby2.3
Java: N/A
Kernel: Linux 4.13.0-36-generic x86_64 GNU/Linux
OS: Ubuntu 17.10 (artful)
Host glibc: 2.26
/usr/bin/gcc: 7.2.0
glibc: N/A
gcc: N/A
xorg: 20170115_1
==> ENV
HOMEBREW_CC: gcc-7
HOMEBREW_CXX: g++-7
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /home/linuxbrew/.linuxbrew
PKG_CONFIG_PATH: /home/linuxbrew/.linuxbrew/opt/zlib/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/openssl/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/ncurses/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/sqlite/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/xz/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/libffi/lib/pkgconfig:/home/linuxbrew/.linuxbrew/opt/python/lib/pkgconfig
ACLOCAL_PATH: /home/linuxbrew/.linuxbrew/share/aclocal
PATH: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super:/home/linuxbrew/.linuxbrew/opt/gdbm/bin:/home/linuxbrew/.linuxbrew/opt/openssl/bin:/home/linuxbrew/.linuxbrew/opt/ncurses/bin:/home/linuxbrew/.linuxbrew/opt/sqlite/bin:/home/linuxbrew/.linuxbrew/opt/xz/bin:/home/linuxbrew/.linuxbrew/opt/bzip2/bin:/home/linuxbrew/.linuxbrew/opt/python/bin:/home/linuxbrew/.linuxbrew/opt/binutils/bin:/home/linuxbrew/.linuxbrew/opt/python/libexec/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: thefuck 3.25 did not build
Logs:
     /home/omer/.cache/Homebrew/Logs/thefuck/05.pip
     /home/omer/.cache/Homebrew/Logs/thefuck/00.options.out
     /home/omer/.cache/Homebrew/Logs/thefuck/05.pip.cc
     /home/omer/.cache/Homebrew/Logs/thefuck/03.pip
     /home/omer/.cache/Homebrew/Logs/thefuck/04.pip
     /home/omer/.cache/Homebrew/Logs/thefuck/01.python2
     /home/omer/.cache/Homebrew/Logs/thefuck/02.python2
READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.
```

**Comment by thedrow** [comment]
I reinstalled Linuxbrew and I still get the same error so there is a problem with the Python formula, I think.

**Comment by thedrow** [comment]
@iMichka Can you take a look?
Also, thefuck is still using Python 2 which should be fixed.

**Comment by thedrow** [comment]
I can confirm that when I switch to Python 3, there are no problems.

**Comment by iMichka** [comment]
I am travelling right now, I hope I can have a look next week.

**Comment by iMichka** [comment]
Can you try again? I think there was a similar error here: #6703, and it was solved by updating.

**Comment by thedrow** [comment]
Yes, sorted. Thank you.
