### ISSUE TITLE
Error: Invalid argument - accept(2) (Windows Subsystem for Linux / Ubuntu 14.04.4 LTS)

### ISSUE THREAD

**Issue by cj** [Linuxbrew/homebrew-core#671]
```
cj@DESKTOP-TMN0MG2:/mnt/c/Users/cjlaz$ brew install openssl --debug
/home/cj/.linuxbrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/cj/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
/home/cj/.linuxbrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/cj/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/makedepend.rb
/home/cj/.linuxbrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/cj/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/home/cj/.linuxbrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/cj/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/zlib.rb
/home/cj/.linuxbrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/cj/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/patchelf.rb
/home/cj/.linuxbrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/cj/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb
sudo: unable to resolve host DESKTOP-TMN0MG2
/home/cj/.linuxbrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /home/cj/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
/home/cj/.linuxbrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/cj/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/zlib.rb
/home/cj/.linuxbrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/cj/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/makedepend.rb
/home/cj/.linuxbrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/cj/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/home/cj/.linuxbrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/cj/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/perl.rb
==> Downloading https://www.openssl.org/source/openssl-1.0.2h.tar.gz
Already downloaded: /home/cj/.cache/Homebrew/openssl-1.0.2h.tar.gz
==> perl ./Configure --prefix=/home/cj/.linuxbrew/Cellar/openssl/1.0.2h_1 --openssldir=/home/cj/.linuxbrew/etc/openssl no-ssl2 zlib-dynamic shared enable-cms -isystem/home/==> make depend
Last 15 lines from /home/cj/.cache/Homebrew/Logs/openssl/02.make:
2016-07-26 10:33:44 -0500

make
depend

making depend in crypto...
make[1]: Entering directory `/tmp/openssl-20160726-3810-3i33hj/openssl-1.0.2h/crypto'
/home/cj/.linuxbrew/bin/makedepend: 2: /home/cj/.linuxbrew/bin/makedepend: Syntax error: "(" unexpected
mv: cannot stat 'Makefile.new': No such file or directory
make[1]: *** [local_depend] Error 2
make[1]: Leaving directory `/tmp/openssl-20160726-3810-3i33hj/openssl-1.0.2h/crypto'
make: *** [depend] Error 1
/home/cj/.linuxbrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/cj/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb
/home/cj/.linuxbrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/cj/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb
/home/cj/.linuxbrew/Library/Homebrew/build.rb (Formulary::TapLoader): loading /home/cj/.linuxbrew/Library/Taps/linuxbrew/homebrew-xorg/xorg.rb
/home/cj/.linuxbrew/Library/Homebrew/debrew.rb:11:in `raise'
```

I've run `brew update`, `brew doctor` and everything is fine.

**Comment by sjackman** [comment]
I haven't seen that error before. Try
```sh
HOMEBREW_MAKE_JOBS=1 brew install openssl
```
Please report
```sh
brew gist-logs openssl
```

**Comment by cj** [comment]
@sjackman same error.  `brew gist-logs openssl` `https://gist.github.com/30065ec36d2b9e460e60a70cf72ba4c`

**Comment by sjackman** [comment]
I think there was a copy-paste error:
```
~ ❯❯❯ curl https://gist.github.com/30065ec36d2b9e460e60a70cf72ba4c
{"error":"Not Found"}
```

**Comment by cj** [comment]
@sjackman ah, sorry about that.  It was missing the `f` https://gist.github.com/30065ec36d2b9e460e60a70cf72ba4cf

**Comment by sjackman** [comment]
```
Kernel: Linux 3.4.0+ x86_64 GNU/Linux
```
https://gist.github.com/anonymous/30065ec36d2b9e460e60a70cf72ba4cf#file-00-config-out-L20
Are you running on Windows Subsystem for Linux?

**Comment by sjackman** [comment]
As a workaround, if you install Linuxbrew in `/home/linuxbrew/.linuxbrew` you can use the precompiled binary bottles.

**Comment by sjackman** [comment]
Once you have a basic system up and running, I'd recommend running `brew install gcc ruby` to upgrade GCC and Ruby.

**Comment by cj** [comment]
Yes, I'm using the Windows Subsystem for Linux.  So, install linuxbrew here? `/home/linuxbrew/.linuxbrew`  I tried running `brew install gcc ruby` and got: https://gist.github.com/cj/6244841a1fafdbd30ec7cd8461461119

**Comment by sjackman** [comment]
I'd like to support Windows Subsystem for Linux, but I'm afraid that I don't have access to a Windows machine on which to test. And these error messages are confounding, to say the least:
```
/home/cj/.linuxbrew/opt/gcc/bin/gcc-5: 1: /home/cj/.linuxbrew/opt/gcc/bin/gcc-5: cannot create ☺H/@@�31@8: Directory nonexistent
/home/cj/.linuxbrew/opt/gcc/bin/gcc-5: 1: /home/cj/.linuxbrew/opt/gcc/bin/gcc-5: ELF☻☺☺☻: not found
/home/cj/.linuxbrew/opt/gcc/bin/gcc-5: 3: /home/cj/.linuxbrew/opt/gcc/bin/gcc-5: Syntax error: "(" unexpected
```
https://gist.github.com/cj/6244841a1fafdbd30ec7cd8461461119#file-gistfile1-txt-L56

My best suggestion for now is to upgrade to Ruby 2.0 either by installing [Traveling Ruby](http://phusion.github.io/traveling-ruby/) using the relevant instructions from here: https://github.com/Linuxbrew/brew/wiki/CentOS5

Or like so:
```sh
apt-get update \
	&& apt-get install -y curl g++ git make ruby2.0 ruby2.0-dev uuid-runtime \
	&& ln -sf ruby2.0 /usr/bin/ruby \
	&& ln -sf gem2.0 /usr/bin/gem
```

**Comment by cj** [comment]
Ok, I upgraded ruby/gem now it just hangs here when running `brew install openssl`

```
cj@DESKTOP-TMN0MG2:/mnt/c/Users/cjlaz$ brew install openssl --debug
/home/cj/.linuxbrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/cj/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
/home/cj/.linuxbrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/cj/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/makedepend.rb
/home/cj/.linuxbrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/cj/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/home/cj/.linuxbrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/cj/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/zlib.rb
/home/cj/.linuxbrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/cj/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/patchelf.rb
/home/cj/.linuxbrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/cj/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb
Error: Invalid argument - accept(2)
/home/cj/.linuxbrew/Library/Homebrew/utils/fork.rb:28:in `accept_nonblock'
/home/cj/.linuxbrew/Library/Homebrew/utils/fork.rb:28:in `block (3 levels) in safe_fork'
/home/cj/.linuxbrew/Library/Homebrew/utils.rb:436:in `ignore_interrupts'
/home/cj/.linuxbrew/Library/Homebrew/utils/fork.rb:26:in `block (2 levels) in safe_fork'
/home/cj/.linuxbrew/Library/Homebrew/utils/fork.rb:7:in `open'
/home/cj/.linuxbrew/Library/Homebrew/utils/fork.rb:7:in `block in safe_fork'
/usr/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
/home/cj/.linuxbrew/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/home/cj/.linuxbrew/Library/Homebrew/formula_installer.rb:610:in `build'
/home/cj/.linuxbrew/Library/Homebrew/formula_installer.rb:238:in `install'
/home/cj/.linuxbrew/Library/Homebrew/cmd/install.rb:288:in `install_formula'
/home/cj/.linuxbrew/Library/Homebrew/cmd/install.rb:149:in `block in install'
/home/cj/.linuxbrew/Library/Homebrew/cmd/install.rb:149:in `each'
/home/cj/.linuxbrew/Library/Homebrew/cmd/install.rb:149:in `install'
/home/cj/.linuxbrew/Library/Homebrew/brew.rb:87:in `<main>'
sudo: unable to resolve host DESKTOP-TMN0MG2
cj@DESKTOP-TMN0MG2:/mnt/c/Users/cjlaz$ /home/cj/.linuxbrew/Library/Homebrew/build.rb:181:in `dump': instance of IO needed (TypeError)
        from /home/cj/.linuxbrew/Library/Homebrew/build.rb:181:in `rescue in <main>'
        from /home/cj/.linuxbrew/Library/Homebrew/build.rb:170:in `<main>'
```

I think the developer preview versions of 10 are free.  If not I can buy you a license.

**Comment by sjackman** [comment]
> I think the developer preview versions of 10 are free.

Where do I download an image of Windows 10 so that I can run it in a virtual machine?

> If not I can buy you a license.

That's kind. Thank you. Let's see if we can get a free copy first.

**Comment by sjackman** [comment]
```
/home/cj/.linuxbrew/Library/Homebrew/utils/fork.rb:28:in `accept_nonblock'
```
That line of Ruby code is:
```ruby
            socket = server.accept_nonblock
```

My guess would be that Windows Subsystem for Linux does not implement the Unix socket call `accept_nonblock`. At first glance, it would be necessary to either rewrite this code without using `accept_nonblock`, or petition Microsoft to implement `accept_nonblock`.

**Comment by JMoVS** [comment]
I think you can download the iso here:
https://www.microsoft.com/de-de/software-download/windows10ISO

and apply for the so called windows insider program here:
https://insider.windows.com/

**Comment by sjackman** [comment]
Thanks. I'll check that out.

**Comment by JMoVS** [comment]
@cj there is a way to install openssl. But how did you update ruby/gem on lxss?
https://github.com/Linuxbrew/homebrew-core/issues/761
