### ISSUE TITLE
ModuleNotFoundError: No module named 'error'

### ISSUE THREAD

**Issue by Elemino** [Linuxbrew/homebrew-core#7392]
```

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/ccm/3.1.4/libexec/bin/ccm", line 7, in <module>
    from ccmlib import common
  File "/home/linuxbrew/.linuxbrew/Cellar/ccm/3.1.4/libexec/lib/python2.7/site-packages/ccmlib/common.py", line 22, in <module>
    import yaml
  File "/home/linuxbrew/.linuxbrew/Cellar/ccm/3.1.4/libexec/vendor/lib/python2.7/site-packages/yaml/__init__.py", line 2, in <module>
    from error import *
ModuleNotFoundError: No module named 'error'
```
Can anyone help with this error I'm getting after running 'ccm create -v 3.9 social' ? Thank you.

**Comment by iMichka** [comment]
Hi. I think this is due to a python/python3 mismatch, after some changes around that in the formula and in brew lately. This rebuild should fix it: #7458

**Comment by iMichka** [comment]
Should be fixed by #7458

**Comment by Elemino** [comment]
Awesome! I'll try it out. Thank you so much for helping.

**Comment by Elemino** [comment]
It works after upgrading ccm which I recall updates linuxbrew and the python libs. Thanks!!!!!  :)
