### ISSUE TITLE
libglade: test fails

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/homebrew-core#929]
```bash
% brew test -v libglade
Testing libglade
==> /usr/bin/gcc-5 test.c -o test -I/home/linuxbrew/.linuxbrew/opt/atk/include/atk-1.0 -I/home/linuxbrew/.linuxbrew/opt/cairo/include/cairo -I/home/linuxbrew/.linuxbrew/opt/fontconfig/include -I/home/linuxbrew/.linuxbrew/opt/freetype/include/freetype2 -I/home/linuxbrew/.linuxbrew/opt/gdk-pixbuf/include/gdk-pixbuf-2.0 -I/home/linuxbrew/.linuxbrew/opt/gettext/include -I/home/linuxbrew/.linuxbrew/opt/glib/include/glib-2.0 -I/home/linuxbrew/.linuxbrew/opt/glib/lib/glib-2.0/include -I/home/linuxbrew/.linuxbrew/opt/gtk+/include/gtk-2.0 -I/home/linuxbrew/.linuxbrew/opt/gtk+/lib/gtk-2.0/include -I/home/linuxbrew/.linuxbrew/Cellar/libglade/2.6.4_1/include/libglade-2.0 -I/home/linuxbrew/.linuxbrew/opt/libpng/include/libpng16 -I/home/linuxbrew/.linuxbrew/opt/pango/include/pango-1.0 -I/home/linuxbrew/.linuxbrew/opt/pixman/include/pixman-1 -D_REENTRANT -L/home/linuxbrew/.linuxbrew/opt/atk/lib -L/home/linuxbrew/.linuxbrew/opt/cairo/lib -L/home/linuxbrew/.linuxbrew/opt/gdk-pixbuf/lib -L/home/linuxbrew/.linuxbrew/opt/gettext/lib -L/home/linuxbrew/.linuxbrew/opt/glib/lib -L/home/linuxbrew/.linuxbrew/opt/gtk+/lib -L/home/linuxbrew/.linuxbrew/Cellar/libglade/2.6.4_1/lib -L/home/linuxbrew/.linuxbrew/opt/pango/lib -latk-1.0 -lcairo -lgdk-quartz-2.0 -lgdk_pixbuf-2.0 -lgio-2.0 -lglade-2.0 -lglib-2.0 -lgobject-2.0 -lgtk-quartz-2.0 -lintl -lpango-1.0 -lpangocairo-1.0 -lxml2
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lgdk-quartz-2.0
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lgtk-quartz-2.0
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lintl
collect2: error: ld returned 1 exit status
Error: libglade: failed
Failed executing: /usr/bin/gcc-5 test.c -o test -I/home/linuxbrew/.linuxbrew/opt/atk/include/atk-1.0 -I/home/linuxbrew/.linuxbrew/opt/cairo/include/cairo -I/home/linuxbrew/.linuxbrew/opt/fontconfig/include -I/home/linuxbrew/.linuxbrew/opt/freetype/include/freetype2 -I/home/linuxbrew/.linuxbrew/opt/gdk-pixbuf/include/gdk-pixbuf-2.0 -I/home/linuxbrew/.linuxbrew/opt/gettext/include -I/home/linuxbrew/.linuxbrew/opt/glib/include/glib-2.0 -I/home/linuxbrew/.linuxbrew/opt/glib/lib/glib-2.0/include -I/home/linuxbrew/.linuxbrew/opt/gtk+/include/gtk-2.0 -I/home/linuxbrew/.linuxbrew/opt/gtk+/lib/gtk-2.0/include -I/home/linuxbrew/.linuxbrew/Cellar/libglade/2.6.4_1/include/libglade-2.0 -I/home/linuxbrew/.linuxbrew/opt/libpng/include/libpng16 -I/home/linuxbrew/.linuxbrew/opt/pango/include/pango-1.0 -I/home/linuxbrew/.linuxbrew/opt/pixman/include/pixman-1 -D_REENTRANT -L/home/linuxbrew/.linuxbrew/opt/atk/lib -L/home/linuxbrew/.linuxbrew/opt/cairo/lib -L/home/linuxbrew/.linuxbrew/opt/gdk-pixbuf/lib -L/home/linuxbrew/.linuxbrew/opt/gettext/lib -L/home/linuxbrew/.linuxbrew/opt/glib/lib -L/home/linuxbrew/.linuxbrew/opt/gtk+/lib -L/home/linuxbrew/.linuxbrew/Cellar/libglade/2.6.4_1/lib -L/home/linuxbrew/.linuxbrew/opt/pango/lib -latk-1.0 -lcairo -lgdk-quartz-2.0 -lgdk_pixbuf-2.0 -lgio-2.0 -lglade-2.0 -lglib-2.0 -lgobject-2.0 -lgtk-quartz-2.0 -lintl -lpango-1.0 -lpangocairo-1.0 -lxml2
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1611:in `block in system'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1548:in `open'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1548:in `system'
/home/linuxbrew/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/libglade.rb:85:in `block in <class:Libglade>'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1449:in `block (2 levels) in run_test'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:775:in `with_logging'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1448:in `block in run_test'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1442:in `run_test'
/home/linuxbrew/.linuxbrew/Library/Homebrew/test.rb:33:in `block in <main>'
/home/linuxbrew/.linuxbrew/Cellar/ruby/2.3.1/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/home/linuxbrew/.linuxbrew/Cellar/ruby/2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/home/linuxbrew/.linuxbrew/Cellar/ruby/2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/home/linuxbrew/.linuxbrew/Cellar/ruby/2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/home/linuxbrew/.linuxbrew/Cellar/ruby/2.3.1/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/home/linuxbrew/.linuxbrew/Library/Homebrew/test.rb:32:in `<main>'
```

**Comment by rwhogg** [comment]
Fixed by https://github.com/Linuxbrew/homebrew-core/pull/931
