### ISSUE TITLE
ruby 2.3.1 - test_minitest_unit.rb (Errno::EACCES)

### ISSUE THREAD

**Issue by tseemann** [Linuxbrew/homebrew-core#988]
Is something broken in my system or is this real?

Logs: https://gist.github.com/73bd2bada4f22f621fb067269095dacb

```
==> Installing ruby                                                                                                ==> Downloading https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.bz2
Already downloaded: /home/linuxbrew/.cache/Homebrew/ruby-2.3.1.tar.bz2
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/ba8cc6b88e6b7153ac37739e5a1a6bbbd8f43817
Already downloaded: /home/linuxbrew/.cache/Homebrew/ruby--patch-929c618f74e89a5e42d899a962d7d2e4af75716523193af42626884eaba1d765.patch
==> Patching
==> Applying mkconfig.patch
patching file tool/mkconfig.rb
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/ruby/2.3.1_1 --enable-shared --disable-silent-rules --wi
==> make
==> make install
Last 15 lines from /home/linuxbrew/.cache/Homebrew/Logs/ruby/03.make:

/tmp/ruby-20161004-114779-18sh8zi/ruby-2.3.1/lib/fileutils.rb:1393:in `initialize': Permission denied @ rb_sysopen - /home/linuxbrew/.linuxbrew/Cellar/ruby/2.3.1_1/lib/ruby/gems/2.3.0/gems/minitest-5.8.3/test/minitest/test_minitest_unit.rb (Errno::EACCES)

        from ./tool/rbinstall.rb:686:in `call'
        from ./tool/rbinstall.rb:686:in `block in <class:Installer>'
        from ./tool/rbinstall.rb:754:in `block (2 levels) in <main>'
        from /tmp/ruby-20161004-99199-uefwx3/ruby-2.3.1/lib/rubygems/specification.rb:821:in `block in each_spec'
        from /tmp/ruby-20161004-99199-uefwx3/ruby-2.3.1/lib/rubygems/specification.rb:743:in `block (2 levels) in each_gemspec'
        from /tmp/ruby-20161004-99199-uefwx3/ruby-2.3.1/lib/rubygems/specification.rb:742:in `each'
        from /tmp/ruby-20161004-99199-uefwx3/ruby-2.3.1/lib/rubygems/specification.rb:742:in `block in each_gemspec'
        from /tmp/ruby-20161004-99199-uefwx3/ruby-2.3.1/lib/rubygems/specification.rb:741:in `each'
        from /tmp/ruby-20161004-99199-uefwx3/ruby-2.3.1/lib/rubygems/specification.rb:741:in `each_gemspec'
        from /tmp/ruby-20161004-99199-uefwx3/ruby-2.3.1/lib/rubygems/specification.rb:819:in `each_spec'
        from ./tool/rbinstall.rb:751:in `block in <main>'
        from ./tool/rbinstall.rb:801:in `block in <main>'
        from ./tool/rbinstall.rb:798:in `each'
        from ./tool/rbinstall.rb:798:in `<main>'
make: *** [do-install-nodoc] Error 1
```

**Comment by sjackman** [comment]
```
Permission denied @ rb_sysopen - /home/linuxbrew/.linuxbrew/Cellar/ruby/2.3.1_1/lib/ruby/gems/2.3.0/gems/minitest-5.8.3/test/minitest/test_minitest_unit.rb (Errno::EACCES)
```
Does the file exist, or is it a permissions issue? Can you please report the output of:
```sh
ls -l /home/linuxbrew/.linuxbrew/Cellar/ruby/2.3.1_1/lib/ruby/gems/2.3.0/gems/minitest-5.8.3/test/minitest/test_minitest_unit.rb
wc /home/linuxbrew/.linuxbrew/Cellar/ruby/2.3.1_1/lib/ruby/gems/2.3.0/gems/minitest-5.8.3/test/minitest/test_minitest_unit.rb
```

**Comment by sjackman** [comment]
> i can’t reinstall ruby - it’s missing: `No such file or directory`

Do you know why it was `Permission denied` previously and now `No such file or directory`?

Are there any versions of `minitest` installed in `/home/linuxbrew/.linuxbrew/Cellar/ruby/2.3.1_1/lib/ruby/gems/2.3.0/gems`?
Does `gem install minitest` work?

**Comment by tseemann** [comment]
I don't have *any* (brew) ruby installed: `/home/linuxbrew/.linuxbrew/Cellar/ruby` is empty.

**Comment by sjackman** [comment]
I'm not sure what's up with the build error, but I've bottled `ruby`.

**Comment by tailriver** [comment]
I've got similar error on CentOS 7.2 (system ruby is `ruby 2.0.0p598 (2014-11-13) [x86_64-linux]`).
Log files in `~/.cache/Homebrew/Logs/ruby` attached.
[logs.zip](https://github.com/Linuxbrew/homebrew-core/files/728684/logs.zip)

**Comment by tailriver** [comment]
Found https://github.com/rubygems/rubygems/issues/1161 and my `/home` is actually on NFS.

**Comment by sjackman** [comment]
If it's a Ruby bug, you can try using [Traveling Ruby](http://phusion.github.io/traveling-ruby/).

**Comment by albertz** [comment]
I get a very similar problem. My home FS is also on NFS.
```
./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems -r./x86_64-linux-fake ./tool/rbinstall.rb --make="make" --dest-dir="" --extout=".ext" --mflags="" --make-flags="" --data-mode=0644 --prog-mode=0755 --installed-list .installed.list --mantype="doc"
installing binary commands:   /u/zeyer/.linuxbrew/Cellar/ruby/2.4.2/bin
/tmp/ruby-20171024-18611-1rggn7l/ruby-2.4.2/lib/fileutils.rb:1290:in `initialize': Permission denied @ rb_sysopen - /u/zeyer/.linuxbrew/Cellar/ruby/2.4.2/bin/ruby (Errno::EACCES)
        from /tmp/ruby-20171024-18611-1rggn7l/ruby-2.4.2/lib/fileutils.rb:1290:in `open'
        from /tmp/ruby-20171024-18611-1rggn7l/ruby-2.4.2/lib/fileutils.rb:1290:in `block in copy_file'
        from /tmp/ruby-20171024-18611-1rggn7l/ruby-2.4.2/lib/fileutils.rb:1289:in `open'
        from /tmp/ruby-20171024-18611-1rggn7l/ruby-2.4.2/lib/fileutils.rb:1289:in `copy_file'
        from /tmp/ruby-20171024-18611-1rggn7l/ruby-2.4.2/lib/fileutils.rb:430:in `copy_file'
        from /tmp/ruby-20171024-18611-1rggn7l/ruby-2.4.2/lib/fileutils.rb:782:in `block in install'
        from /tmp/ruby-20171024-18611-1rggn7l/ruby-2.4.2/lib/fileutils.rb:1461:in `block in fu_each_src_dest'
        from /tmp/ruby-20171024-18611-1rggn7l/ruby-2.4.2/lib/fileutils.rb:1475:in `fu_each_src_dest0'
        from /tmp/ruby-20171024-18611-1rggn7l/ruby-2.4.2/lib/fileutils.rb:1459:in `fu_each_src_dest'
        from /tmp/ruby-20171024-18611-1rggn7l/ruby-2.4.2/lib/fileutils.rb:778:in `install'
        from ./tool/rbinstall.rb:166:in `install'
        from ./tool/rbinstall.rb:346:in `block in <main>'
        from ./tool/rbinstall.rb:822:in `block in <main>'
        from ./tool/rbinstall.rb:819:in `each'
        from ./tool/rbinstall.rb:819:in `<main>'
uncommon.mk:284: recipe for target 'do-install-nodoc' failed
make: *** [do-install-nodoc] Error 1
```

**Comment by sjackman** [comment]
Please report the output of…
```sh
ls -l /u/zeyer/.linuxbrew/Cellar/ruby/2.4.2/bin/ruby
/u/zeyer/.linuxbrew/Cellar/ruby/2.4.2/bin/ruby --version
```

**Comment by albertz** [comment]
Well, it's not installed because the brew failed with the error I just wrote. So of course I get:
```
ls: cannot access '/u/zeyer/.linuxbrew/Cellar/ruby/2.4.2/bin/ruby': No such file or directory
```

**Comment by sjackman** [comment]
Ah, I see. That was permission denied while writing. I had thought reading.
Do you have write permissions for each subdirectory above that path?

**Comment by albertz** [comment]
Yes. Except `/u` and `/`. But as said, all is on a NFS share. I suspect that this is related to the problem.

**Comment by sjackman** [comment]
Possibly related. I primarily use Linuxbrew on NFS though, so not all NFS installations are problematic, though yours may be. Please report the output of…
```sh
brew install hello
brew gist-logs hello
```

**Comment by albertz** [comment]
```
zeyer@sulfid ~> brew install hello
Updating Homebrew...
...
==> Downloading https://linuxbrew.bintray.com/bottles/hello-2.10.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring hello-2.10.x86_64_linux.bottle.tar.gz
  /u/zeyer/.linuxbrew/Cellar/hello/2.10: 52 files, 227.9KB

zeyer@sulfid ~> brew gist-logs hello
Error: No logs.
```

**Comment by albertz** [comment]
Btw, related might also be [this similar Python issue](https://github.com/Linuxbrew/homebrew-core/issues/4799). There the issue is in the Python `shutil.copy*` functions which try to copy the xattr and that fails for "system.nfs4_acl" which is read-only on NFS. See [here](https://bugs.python.org/issue24564). Maybe Ruby tries to do sth similar here.

**Comment by sjackman** [comment]
```
Permission denied @ rb_sysopen - /u/zeyer/.linuxbrew/Cellar/ruby/2.4.2/bin/ruby (Errno::EACCES)
```

I don't have any leads for you, other than it looks like a permissions issue. Sorry that I couldn't be of more help, Albert.
